README: Доработал Overview секцию (head)
feature-sliced/wiki pull request #101
Opened 2021-04-21 23:08 UTC by martis-git

## CHANGELOG

- Добавил описание для Overview секции
- Добавил базовый каркас для подсекций Overview (concepts, motivation)
- Поправил немного статью по требованиям к архитектуре

## Чеклист

- [ ] `docs` Использованы github-дискуссии (не было нужды)

- [ ] `by-issue` Проведена проверка по требованиям задачи

- [ ] Проведено self-review изменений

2021-04-22 11:35 UTC, martis-git commented on README.md
> +[`Public API`](./concepts/public-api.md), [`Isolation`](./concepts/cross-communication.md), ...
> `TODO:` Не моя часть, но базово разметил (будет дорасписано Виктором по его задаче)

2021-04-22 11:35 UTC, martis-git commented on README.md
> +
> `TODO:` Не моя часть, но базово разметил (будет дорасписано Олегом по его задаче)

2021-04-22 11:35 UTC, martis-git commented on README.md
> +[`Public API`](./concepts/public-api.md), [`Isolation`](./concepts/cross-communication.md), ...
> `TODO:` Не моя часть, но базово разметил (будет дорасписано Виктором по его задаче)

2021-04-22 16:51 UTC, AlexandrHoroshih requested changes

2021-04-22 16:51 UTC, AlexandrHoroshih commented on README.md
> +Стандартизация проектных знаний и решений, подкрепленная обширным опытом разработки.
Как-то тяжело читается
Может что-нибудь в духе?

_Обычно конкретные подходы построения фронтендовой архитектуры не выходят за рамки проектных знаний и переизобретаются с нуля от проекта к проекту, несмотря на то, что специфика самих проектов часто отличается не так значительно._

_Вместо того, чтобы придумывать, и документировать это каждый раз, хочется иметь обобщить опыт и проектные знания и сформировать рабочую и задокументированную методологию_

2021-04-22 20:14 UTC, martis-git commented on README.md
> +Стандартизация проектных знаний и решений, подкрепленная обширным опытом разработки.
Стоило убрать из кода в комментарии 😄 

![image](https://user-images.githubusercontent.com/42924400/115779243-67798e80-a3c0-11eb-96cb-96f72b18437f.png)

2021-04-24 16:05 UTC, sergeysova approved these changes

2021-04-25 08:45 UTC, AlexandrHoroshih approved these changes

2021-04-25 08:50 UTC, merged