Feat/readme-overview
feature-sliced/wiki pull request #102
Opened 2021-04-22 16:09 UTC by OlegBrony

## CHANGELOG

Добавлен Overview блок.

2021-04-22 16:39 UTC, AlexandrHoroshih commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
Круто сформулировано кстати

2021-04-22 16:39 UTC, AlexandrHoroshih submitted a review, later dismissed

2021-04-22 20:11 UTC, martis-git requested changes
Ну как обсуждали:
- Убрать лишнее
- Оставшееся сократить
- Убедиться, что передана основная мысль по мотивации

2021-04-22 20:11 UTC, martis-git commented on README.md
> +  > </details>
Как уже обсуждали:
1. Убери все спойлеры (для README они тем более не нужны)
2. Постарайся ужать инфу до 5-6 строчек

2021-04-22 20:11 UTC, martis-git commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
Соглы, здесь тоже в свое время его указал)

https://github.com/feature-sliced/wiki/blob/master/about/motivation.md#-%D1%81%D0%BC-%D1%82%D0%B0%D0%BA%D0%B6%D0%B5

2021-04-22 20:11 UTC, martis-git commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
Вот это оч хорошие мысли, про которые я и в motivation вродь писал в какой-то мере

Но для README, особенно после сегодняшнего, согласись - немного громоздко)

Предлагаю положить этот фрагмент [сюда в комменты с пометкой Карине](https://github.com/feature-sliced/wiki/issues/103), а в Motivation - оставить только самое смачное и нужное (как обсуждали)

> Плюс опять же - можешь глянуьт примерно как я [расписал для каркаса](https://github.com/feature-sliced/wiki/issues/93#issuecomment-824429809)

2021-04-22 20:11 UTC, martis-git commented on about/motivation.md
> +    >
По-моему в этом файле лучше убрать все лишние изменения)

> ![image](https://user-images.githubusercontent.com/42924400/115778625-a0653380-a3bf-11eb-9175-b1614a4550d5.png)

2021-04-22 20:11 UTC, martis-git commented on README.md
> +## 🐛 The Problem
Некритично, но я бы пока убрал эмоджи из README

> Далеко не факт что они в доках останутся, но тут пока лучше к более "стандартному виду" прийти
>
> Да, я знаю примеры, где и в ридми юзалось - но их крайне мало

2021-04-22 20:11 UTC, martis-git commented on README.md
> +## 🐛 The Problem
Плюс секция больше все же про "Motivation" , а не про проблемы)

> Это снова к вопросу - о чем больше писать - о проблемах, или в совокупе о проблемах/целях и мотивации в целом)

2021-04-22 20:13 UTC, martis-git commented
@OlegBrony , глянь тож

Вот еще @AlexandrHoroshih [хорошо набросил формулировку](https://github.com/feature-sliced/wiki/pull/101/files#r618579825)

![image](https://user-images.githubusercontent.com/42924400/115779160-487afc80-a3c0-11eb-8962-0e5b588b1ded.png)

2021-04-25 08:54 UTC, martis-git commented
@OlegBrony добей PR пож

2021-04-25 10:39 UTC, OlegBrony commented on about/motivation.md
> +    >
я убрал все изменения из motivation страницы

2021-04-25 10:43 UTC, martis-git commented on about/motivation.md
> +    >
Содержательно - да, но при этом все равно "зацепил" форматирование и прочее)

![image](https://user-images.githubusercontent.com/42924400/115990480-235ad980-a5cc-11eb-9c48-d1d196d6c11b.png)

2021-04-25 10:43 UTC, martis-git commented on about/motivation.md
> +    >
> Ты зайди в diff этого файла у пулл-реквеста, поймешь о чем я

2021-04-25 10:44 UTC, OlegBrony commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
я не понимаю проблемы... громозким вроде не кажется, вроде как описывает цель проекта, как лучше сделать? просто вырезать этот кусок и вставить в motivation?

2021-04-25 10:50 UTC, martis-git commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
<details>
<summary>1. Помнишь что обсуждали на последнем созвоне?</summary>

**Про то, что мы в доке оч часто разворачиваем все-все знания, которые имеем и хотим поделиться**

Хотя возможно - это не всегда нужно, и такие мысли стоит поместить куда-то в `/src/blog` (чем @karina-drummer и занимается по задаче как раз - #103 )



> Да и diataxis.fr/ который мы скоро затащим себе - об этом же говорит

</details>

<details>
<summary>2. Также мы обсуждали, что в README должна быть только самая-самая важная инфа, без погружения в детали</summary>

![image](https://user-images.githubusercontent.com/42924400/115990617-e0e5cc80-a5cc-11eb-8991-12233027c8e8.png)

</details>

---

Поэтому и говорю - постарайся оставить только самое важное из того что написал (остальное не потеряется и пойдет в другие доки - но для README явно выглядит громоздко)

> Это скорее значит - что не нужно так подробно писать про проектные знания и проч - а лучше скорее их упомянуть, и сослаться позже на отдельный документ, который бы расписывал - как методология помогает с ними обходиться проще

2021-04-25 10:51 UTC, martis-git commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
**Посмотри в качестве примера, как сейчас сделано в мастер ветке в README**

> Я там каркас базовый сделал - но лучше опять же - посмотри с контекстом того, что уже есть - и возможно эту часть можно еще улучшить/отшлифовать

2021-05-05 15:46 UTC, martis-git commented
Спасибо большое за формулировку секции @OlegBrony  и @AlexandrHoroshih

2021-05-05 15:53 UTC, martis-git approved these changes
self-approve)

2021-05-05 15:57 UTC, karina-jovian commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
После "зная это" нужна запятая

feature-sliced **создаётся** ( потому что речь о методологии а не о слайсах )

2021-05-05 16:06 UTC, martis-git commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
А-ой, боюсь ты старую версию доки смотришь)

![image](https://user-images.githubusercontent.com/42924400/117173046-0ba60100-add5-11eb-8bcf-e1a7bb3f6973.png)

2021-05-05 16:07 UTC, martis-git commented on README.md
> +отвечающую за архитектуру в третью группу — технологический стек.
Комменты старые уже, я сегодня так многое поменял

Лучше через вкладку "files"

2021-05-05 16:34 UTC, martis-git commented
@feature-sliced/reviewers

2021-05-05 18:15 UTC, AlexandrHoroshih approved these changes

2021-05-06 08:49 UTC, martis-git commented
@feature-sliced/core нужен еще один аппрув

2021-05-07 10:57 UTC, martis-git approved these changes

2021-05-07 13:25 UTC, binjospookie approved these changes

2021-05-07 13:44 UTC, merged