Feature/mvp/readme head
feature-sliced/wiki pull request #110
Opened 2021-05-05 14:12 UTC by martis-git

## CHANGELOG

## Чеклист

- [ ] `docs` Использованы github-дискуссии (не потребовалось)

- [x] `by-issue` Проведена проверка по требованиям задачи

- [ ] Проведено self-review изменений

2021-05-05 14:13 UTC, martis-git commented on README.md
> +> <sup>**только на свой страх и риск*</sup>
Не нашель альтернативы на md 🤷‍♀️

2021-05-05 14:15 UTC, martis-git commented on README.md
Раздел с мотивацией вынесу выше по PR #102

2021-05-05 14:30 UTC, martis-git commented
@sergeysova особенно пристально посмотри пож)

2021-05-05 16:34 UTC, martis-git commented
@feature-sliced/reviewers

2021-05-05 18:13 UTC, AlexandrHoroshih requested changes

2021-05-05 18:13 UTC, AlexandrHoroshih commented on README.md
> +Методология, помогающая определять в Frontend проектах разбиение модулей и связи между ними.
Как-то сложно читается, на мой взгляд.
Может, как-то так?
```suggestion
Методология, помогающая проектировать фронтенд-проекты как композицию отдельных модулей, разделенных по областям ответственности
```

2021-05-05 18:13 UTC, AlexandrHoroshih commented on README.md
>  В соответствие с ней, становится проще поддерживать и адаптировать изменяющуюся функциональность приложений.
Тоже как-то сложно читается, как по мне. 
Как насчет такого?
```suggestion
В соответствие с ней, фронтенд-проекты становится проще поддерживать и адаптировать к новым условиям, если такие возникают
```

2021-05-05 19:55 UTC, martis-git commented on README.md
> +Методология, помогающая определять в Frontend проектах разбиение модулей и связи между ними.
Вот тут хз даж)
Я исходил из определения [feature-driven](https://slides.com/kof/feature-driven-architecture#/12)

![image](https://user-images.githubusercontent.com/42924400/117201184-035dbe00-adf5-11eb-9535-6646166d1134.png)

2021-05-05 19:58 UTC, martis-git commented on README.md
> +Методология, помогающая определять в Frontend проектах разбиение модулей и связи между ними.
Ну и [это](https://featureslices.dev/) офк
![image](https://user-images.githubusercontent.com/42924400/117201455-559edf00-adf5-11eb-9201-f7c0e0ffa937.png)

2021-05-06 06:03 UTC, AlexandrHoroshih commented on README.md
> +Методология, помогающая определять в Frontend проектах разбиение модулей и связи между ними.
В целом, меня в твоем варианте смущает только **определять разбиение модулей** - как по мне, очень странно звучит.
Ну и нас ведь разбиение не любым способом, а вполне конкретным - кажется, тоже стоит сразу об этом упомянуть

2021-05-06 06:05 UTC, AlexandrHoroshih commented on README.md
> +Методология, помогающая определять в Frontend проектах разбиение модулей и связи между ними.
"Набор принципов, который помогает вам определить границы" в нашем случае это ведь как раз "границы областей ответственности при разделении по модулям"? Так что вроде противоречия нет

2021-05-06 06:09 UTC, martis-git commented on README.md
> +Методология, помогающая определять в Frontend проектах разбиение модулей и связи между ними.
Выбрал что-то промежуточное из всего крч)

2021-05-06 06:18 UTC, martis-git commented on README.md
> +Методология, помогающая определять в Frontend проектах разбиение модулей и связи между ними.
@AlexandrHoroshih только щас увидел твои комменты)

Вродь в новом варианте это тож учел - глянь пож

2021-05-06 08:49 UTC, martis-git commented
@feature-sliced/core нужно два аппрува

@sergeysova - особенно твое ревью нужно

2021-05-06 09:24 UTC, AlexandrHoroshih commented on README.md
> +Методология для проектирования *frontend проектов*, помогающая **разбиению и композиции модулей согласно областям ответственности.**
**разбиение модулей** всё еще кажется мне очень странно звучащей фразой

2021-05-06 09:25 UTC, AlexandrHoroshih commented on README.md
> +Методология для проектирования *frontend проектов*, помогающая **разбиению и композиции модулей согласно областям ответственности.**
Типа, мы же разбиваем **на** модули
Хз, возможно, я излишне докапываюсь тут

2021-05-06 10:15 UTC, martis-git commented on README.md
> +- Предлагает разделять проект согласно [**бизнес-юнитам**][refs-ext-ubiq-lang]
> Больше ссылок - богу ссылок!

Если слишком много референсов - дайте знать)

2021-05-06 10:18 UTC, AlexandrHoroshih submitted a review, later dismissed

2021-05-07 14:47 UTC, karina-jovian commented on README.md
> +> <sup>**только на свой страх и риск*</sup>
Эту фразу достаточно выделить жирным шрифтом, но она вообще тут не нужна, выше и так написано что not production-ready

2021-05-07 15:09 UTC, martis-git commented on README.md
> +> <sup>**только на свой страх и риск*</sup>
>  но она вообще тут не нужна

Я пробовал оставить без нее

Тогда складывается ощущение, что методология вообще сырая и даж рассматривать ее не особо имеет смысл

А то что мы подразумевали "онли на ваш страх и риск и вы знаете что делаете" - не особо читается между строк

Поэтому решил оставить

*А жирный шрифт как по мне - тут наоборот не подходит - т.к. цель была сделать "маленькую" ремарку, которая и была бы заметна, но на остальном фоне привлекала бы меньше внимания*

2021-05-08 15:28 UTC, AlexandrHoroshih approved these changes

2021-05-08 15:40 UTC, martis-git commented
@sergeysova глянь пож

2021-05-09 09:03 UTC, sergeysova requested changes

2021-05-09 09:03 UTC, sergeysova commented on README.md
> +В соответствие с ней, фронтенд-проекты становится проще поддерживать и адаптировать к возникающим новым условиям.
"становится проще" это субъективная характеристика. Здесь нужно доказать как проще, и почему это "проще" действительно объективно

2021-05-09 09:03 UTC, sergeysova commented on README.md
> +</details>
```suggestion
![visual_schema](./assets/visual_schema.jpg)

</details>
```

Между html тегами и markdown разметкой должен быть хотя бы один отступ, иначе может ломаться совсем неожиданно

2021-05-09 09:03 UTC, sergeysova commented on README.md
> +> Подробнее - ["Абстракции методологии"](./intro/abstractions.md) и ["Разбиение приложения"](./concepts/app-splitting.md)
Имхо, не стоит использовать цитаты так

```suggestion
Подробнее в ["Абстракции методологии"](./intro/abstractions.md) и ["Разбиение приложения"](./concepts/app-splitting.md)
```

2021-05-09 09:03 UTC, sergeysova commented on README.md
> +  - [Доклад React SPB Meetup#1 - Feature Slices](https://t.me/feature_slices)
```suggestion
  - [Доклад React SPB Meetup #1 - Feature Slices](https://t.me/feature_slices)
```

2021-05-09 09:33 UTC, martis-git commented on README.md
> +> <sup>**только на свой страх и риск*</sup>
@sergeysova @karina-jovian оке, оставил тогда просто italic

![image](https://user-images.githubusercontent.com/42924400/117567023-b6af0700-b0c2-11eb-8b23-4903141bccdc.png)

2021-05-09 10:55 UTC, martis-git commented on README.md
> +[ext-discussions]: https://github.com/feature-sliced/wiki/discussions
`ext-`, `refs-` префиксы добавил, т.к. ссылки бывают разных видов

По опыту могу сказать - что так гораздо проще, чем если линки будут составляться исключительно по имени

> @karina-jovian на случай, если захочешь докопаться до этого))

2021-05-09 10:56 UTC, martis-git commented on README.md
> +[ext-discussions]: https://github.com/feature-sliced/wiki/discussions
Вынес также все переменные наверх, чтобы было проще управлять ссылками и снизить вероятность ошибиться
(а то там уже порядочно референсов накопилось)

2021-05-09 11:05 UTC, martis-git commented on README.md
> +[ext-discussions]: https://github.com/feature-sliced/wiki/discussions
Также это упрощает разработку и ревью исходника доки, т.к. ссылки занимают гораздо меньше места

2021-05-09 11:06 UTC, martis-git commented on README.md
> +    > Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности кастомизировать логику модуля без оверхедных переопределений*
Развернул объяснение профита от методологии по просьбе @sergeysova

2021-05-09 19:18 UTC, martis-git commented
@feature-sliced/core Внес правки, теперь вроде ок должно быть

Гляньте пож

2021-05-09 20:35 UTC, martis-git commented on README.md
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности кастомизировать логику модуля без оверхедных переопределений*
Сократить смог только заголовки (@karina-jovian , @ilyaagarkov )

Но основное содержание пришлось оставить как есть  - иначе смысл теряется (@sergeysova )

2021-05-10 07:18 UTC, ilyaagarkov approved these changes

2021-05-10 09:50 UTC, sergeysova approved these changes

2021-05-10 10:31 UTC, merged