Доработал структуру доки согласно diataxis (divio)
feature-sliced/wiki pull request #111
Opened 2021-05-06 22:04 UTC by martis-git

## CHANGELOG

- Довел структуру до diataxis формата
- Спасибо за идею с рут `/src` папкой - @karina-jovian 
- В основном вдохновился [докой snowpack](https://www.snowpack.dev/) и прочих  в качестве нейминга основных папко
   > snowpack тоже использует diataxis "под капотом"

## Чеклист

- [ ] `docs` Использованы github-дискуссии

- [x] `by-issue` Проведена проверка по требованиям задачи

- [ ] Проведено self-review изменений

2021-05-07 05:36 UTC, AlexandrHoroshih approved these changes

2021-05-07 14:45 UTC, karina-jovian requested changes

2021-05-07 14:45 UTC, karina-jovian commented on docs/concepts/cross-communication.md
> +В рамках методологии все модули [**распределены по слоям (слайсам)**](../docs/references/abstractions.md#-group-slices) - зонам ответственности. Слои, в свою очередь, организованы вертикально: "внизу
>все модули

Очень абстрактно и размыто, из формулировки можно подумать, что распределение по слоям есть на всех уровнях. Думаю, лучше написать "В рамках методологии приложение делится на зоны ответственности, называемые слоями"

>распределены по слоям (слайсам)

Смешивается понятие слоёв и слайсов. В данном случае речь идёт только о слоях.

>организованы вертикально

Во-первых, оборот "организован" отсылает ко внутренней структуре, а не внешней. Если исключения и бывают, то они очень редки.
Во-вторых, считаю, что нет смысла указывать на вертикальную природу структуры, когда речь и так идёт о слоях

>"внизу" находятся...

Самый нижний слой содержит...

>по мере продвижения "вверх"...

В верхних слоях...

2021-05-07 14:45 UTC, karina-jovian commented on docs/concepts/cross-communication.md
> +Независимо от принадлежности к какому либо слайсу каждый модуль [**обязан предоставлять публичный интерфейс доступа**](./public-api.md).
к **какому-либо** слайсу **,** ...

( не хватает дефиса и запятой )

2021-05-07 14:45 UTC, karina-jovian commented on docs/get-started/readme.md
> +> Пока здесь нет содержания :/
TBD

2021-05-07 14:45 UTC, karina-jovian commented on docs/get-started/faq.md
> +> Временно пусто
TBD

2021-05-07 14:45 UTC, karina-jovian commented on docs/get-started/.gitkeep
> +[EXPLANATION] Get-started, Overview
`.keep` файлы подразумеваются не имеющими содержание

`.placeholder` в этом плане более явное имя

2021-05-07 14:52 UTC, martis-git commented on docs/concepts/cross-communication.md
> +В рамках методологии все модули [**распределены по слоям (слайсам)**](../docs/references/abstractions.md#-group-slices) - зонам ответственности. Слои, в свою очередь, организованы вертикально: "внизу
Боюсь, по данному PR больше вопрос **структуры**, а не **содержания**)

2021-05-08 15:29 UTC, AlexandrHoroshih approved these changes

2021-05-08 15:40 UTC, martis-git commented
@karina-jovian глянь еще раз пож

2021-05-09 08:57 UTC, sergeysova approved these changes

2021-05-09 09:13 UTC, merged