feat(migration-from-v1): add basis
feature-sliced/wiki pull request #114
Opened 2021-05-12 21:14 UTC by martis-git

## CHANGELOG

- Добавил гайд по миграции с feature-slices (v1)

## Чеклист

- [x] `docs` Использованы github-дискуссии (чат комьюнити)

- [x] `by-issue` Проведена проверка по требованиям задачи

- [ ] Проведено self-review изменений

2021-05-13 18:49 UTC, martis-git commented on docs/guides/migration-from-v1.md
> +    - `shared/lib` - Набор вспомогательных библиотек для реализации логики (без свалки хелперов)
Думал также сделать это в виде таблицы - но тогда немного всрато будет это выглядеть, да и поддерживать тож не оч

2021-05-13 20:58 UTC, martis-git commented on docs/guides/migration-from-v1.md
> +- будет развиваться в дальнейшем тулкит для соблюдения концепций и конвенций по архитектуре
Вот здесь мог оч много булшита написать - поэтому перепроверьте лучше пож))

2021-05-13 21:13 UTC, martis-git commented on docs/guides/migration-from-v1.md
> +Теперь гораздо проще [соблюдать принцип низкой связности](low-coupling.md) между модулями, благодаря новым слоям.
Будет готово, когда @AlexandrHoroshih допилит свою часть

2021-05-14 05:35 UTC, martis-git commented on docs/guides/migration-from-v1.md
> +Теперь гораздо проще [соблюдать принцип низкой связности](low-coupling.md) между модулями, благодаря новым слоям.
**вернее ссылка будет работать, когда статью допилят*

2021-05-14 05:37 UTC, martis-git commented
@feature-sliced/reviewers можете смотреть)

2021-05-14 15:59 UTC, sergeysova requested changes

2021-05-14 15:59 UTC, sergeysova commented on docs/guides/migration-from-v1.md
> +> `WIP:` Поскольку на данный момент - работа над этой версией методологии в процессе, ее внедрение **в рабочие проекты пока что не рекомендуется** *(только на свой страх и риск)*
```suggestion
`WIP:` Поскольку на данный момент - работа над этой версией методологии в процессе, ее внедрение **в рабочие проекты пока что не рекомендуется** *(только на свой страх и риск)*
```

2021-05-14 15:59 UTC, sergeysova commented on docs/guides/migration-from-v1.md
> +    - *Примеры: `user`, `i18n`, `order`*
```suggestion
    - *Примеры: `current-user`, `i18n`, `order`, `blog`*
```

2021-05-14 15:59 UTC, sergeysova commented on docs/guides/migration-from-v1.md
> +    - *Прежние варианты: `shared`, `common`, `lib`*
```suggestion
- `/app` — **слой инициализации приложения**
    - *Прежние варианты: `app`, `core`, `init`, `src/index` (и такое бывает)*
- `/processes` — [**слой бизнес-процессов**][disc-process]
    - *Прежние варианты: `processes`, `flows`, `worfklows`*
- `/pages` — **слой страниц приложения**
    - *Прежние варианты: `pages`, `screens`, `views`, `layouts`*
- `/features` — [**слой частей функциональности**][disc-features]
    - *Прежние варианты: `features`, `containers`*
- `/entities` — [**слой бизнес-сущностей**][disc-entities]
    - *Прежние варианты: `entities`, `models`, `shared`*
- `/shared` — [**слой переиспользуемого инфраструктурного кода**][disc-shared] 🔥
    - *Прежние варианты: `shared`, `common`, `lib`*
```

2021-05-14 15:59 UTC, sergeysova commented on docs/guides/migration-from-v1.md
> +    - *Прежние варианты: `config`, `env`, `get-env`*
```suggestion
- `/ui` — [**UI-сегмент**][disc-ui] 🔥
  - _Прежние варианты: `ui`, `components`, `view`_
- `/model` — [**БЛ-сегмент**][disc-model] 🔥
  - _Прежние варианты: `model`, `store`, `state`, `services`, `controller`_
- `/lib` — сегмент **вспомогательного кода**
  - _Прежние варианты: `lib`, `libs`, `utils`, `helpers`_
- `/api` — [**API-сегмент**][disc-api]
  - _Прежние варианты: `api`, `service`, `requests`, `queries`_
- `/config` — **сегментом конфигурации приложения** стоит
  - _Прежние варианты: `config`, `env`, `get-env`_
```

2021-05-15 05:07 UTC, martis-git commented on docs/guides/migration-from-v1.md
> +> `WIP:` Поскольку на данный момент - работа над этой версией методологии в процессе, ее внедрение **в рабочие проекты пока что не рекомендуется** *(только на свой страх и риск)*
Мыж вроде условились, что сноски использовать можно, но для всяких примечаний вне контекста, не?)

Да и если глянуть без сноски - то контексты тут размываются сильно, хотя эта сноска - именно временное решение-предупреждение
![image](https://user-images.githubusercontent.com/42924400/118348641-6ae1df00-b554-11eb-9b4a-40c1fce7c7f4.png)

2021-05-15 05:08 UTC, martis-git commented on docs/guides/migration-from-v1.md
> +    - *Примеры: `user`, `i18n`, `order`*
>     - *Примеры: `current-user`, `i18n`, `order`, `blog`*

См. [PR по вьюверу)](https://github.com/feature-sliced/wiki/pull/115)

2021-05-15 05:08 UTC, martis-git commented on docs/guides/migration-from-v1.md
> +    - *Примеры: `user`, `i18n`, `order`*
Но про блог добавлю, оке

2021-05-15 14:33 UTC, AlexandrHoroshih approved these changes

2021-05-15 20:05 UTC, martis-git commented
Ситуация на 15.05, 23:05

![image](https://user-images.githubusercontent.com/42924400/118376651-02394780-b5d2-11eb-8db1-02b9c81932ab.png)

2021-05-15 20:12 UTC, merged