Добавил гайд-пример по работе с текущим авторизованным пользователем (Viewer/Principle/Session)
feature-sliced/wiki pull request #115
Opened 2021-05-12 22:05 UTC by martis-git

## CHANGELOG

Добавил гайд-пример по работе с текущим авторизованным пользователем (Viewer/Principle/Session)

## Чеклист

- [ ] `docs` Использованы github-дискуссии

- [ ] `by-issue` Проведена проверка по требованиям задачи

- [ ] Проведено self-review изменений

2021-05-13 17:41 UTC, AlexandrHoroshih commented on docs/guides/examples/viewer.md
> +export const $userStore = createStore(...);
Небольшой коммент: постфикс Store излишен, т.к. $ в начале уже обозначает стор

2021-05-13 18:11 UTC, martis-git commented on docs/guides/examples/viewer.md
> +export const $userStore = createStore(...);
Спс)

Хотя это драфт еще конечн

2021-05-14 08:08 UTC, martis-git commented on docs/guides/examples/readme.md
> +> `TBD`
Пока что пусть пустует, т.к. будут добавляться еще другие примеры

Потом когда буду вливать PR-ы - добавлю все линки

2021-05-14 08:09 UTC, martis-git commented on docs/guides/examples/viewer.md
> +> *Реализация в ваших проектах может отличаться, методология, опять же, никак не регламентирует эти аспекты*
Ну пытался без этого, но тогда 
- либо совсем убирать упоминание (и тогда возникнут вопросы/комментарии "А надо было реализовывать по другому!")
- либо добавлять эту сноску у каждой секции (что тож не оч)

2021-05-14 08:09 UTC, martis-git commented on docs/guides/examples/viewer.md
> +```
Решил не усложнять структуру в каждой секции:
- Пусть на секции отобразиться лишь один из примеров для конкретного слоя
- При этом ниже будет дополнение про другие существующие примеры применения слоя

2021-05-14 08:14 UTC, martis-git commented on docs/guides/examples/viewer.md
> +
Показалось также логичным, добавлять подобные вставки - чтобы не оставалось вопросов **"Оке, у меня есть такой модуль - а что он может использовать? А кем может быть использован?"**

2021-05-14 16:58 UTC, AlexandrHoroshih requested changes

2021-05-14 16:58 UTC, AlexandrHoroshih commented on docs/guides/examples/viewer.md
> +Обычный Public API модуля
Думаю, имеет сделать **Public API модуля** ссылкой на статью - чтобы можно было сходу посмотреть, что имеется ввиду

2021-05-14 16:58 UTC, AlexandrHoroshih commented on docs/guides/examples/viewer.md
> +- В силу специфики слоя, используется не всегда - **только когда логика размывается в страницах** и нужно **отдельное управление контекстом** на сразу нескольких страницах
Вот здесь бы, в дополнение к уже написанному, как-то более явно сказать, мол, **слой процессов - опциональный**

2021-05-15 14:31 UTC, AlexandrHoroshih approved these changes

2021-05-15 20:05 UTC, martis-git commented
Ситуация на 15.05, 23:04

![image](https://user-images.githubusercontent.com/42924400/118376644-f6e61c00-b5d1-11eb-8834-991ecef04f57.png)

2021-05-15 20:07 UTC, merged