Feature/mvp/readme refinements
feature-sliced/wiki pull request #116
Opened 2021-05-13 15:28 UTC by martis-git

## CHANGELOG

- Доработал README
- Внес запрашиваемые правки

## Чеклист

- [ ] `docs` Использованы github-дискуссии

- [ ] `by-issue` Проведена проверка по требованиям задачи

- [ ] Проведено self-review изменений

2021-05-13 18:14 UTC, martis-git commented on README.md
> +# feature-sliced
Было два стула

<table>
<td>

![image](https://user-images.githubusercontent.com/42924400/118167952-f7df4800-b42f-11eb-918a-a4153fbb9523.png)
</td>
<td>

![image](https://user-images.githubusercontent.com/42924400/118167969-fada3880-b42f-11eb-9ef3-26e19f3a476c.png)
</td>


</table>

Решил выбрать компромиссный промежуточный вариант, чтобы совсем *вырвиглазно* не было)

2021-05-13 18:16 UTC, martis-git commented on README.md
> +> **Примечание:** В большинстве случаев рекомендуется располагать `api` и `config` только на shared-слое
По задумке @ilyaagarkov )

2021-05-13 18:18 UTC, martis-git commented
README вышел толстым, но зато содержательным вродь)

2021-05-13 18:23 UTC, AlexandrHoroshih approved these changes

2021-05-13 19:23 UTC, martis-git commented on README.md
> +> **Примечание:** В большинстве случаев рекомендуется располагать `api` и `config` только на shared-слое
Аж такое нарыл

![image](https://user-images.githubusercontent.com/42924400/118176269-e13dee80-b439-11eb-8435-8dc73120e3a1.png)

2021-05-13 21:22 UTC, martis-git commented
@AlexandrHoroshih добавил правки от Карины - переОКни пож)

2021-05-13 21:50 UTC, karina-jovian requested changes

2021-05-13 21:50 UTC, karina-jovian commented on README.md
>  И поэтому - вместо того, чтобы придумывать и документировать это каждый раз - хочется **обобщить опыт и сформировать рабочую, проверенную и задокументированную методологию** для проектирования архите
Замени тире на запятые

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> -[refs-knowledges]: /docs/references/knowledge-types.md
knowledge нельзя использовать во множественном числе

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +*Да, практик и паттернов - много (`SOLID`, `GRASP`, `DDD`, ...)*
Лишнее тире

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +*Но для фронтенда - [крайне трудно найти][refs-motivation] устоявшиеся и конкретные подходы*
Лишнее тире

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +Обычно, подходы построения архитектуры фронтенда от проекта к проекту - [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]
Лишнее тире

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +- Для подключения в другие модули, без нужды лезть во внутренности данного модуля
Лишняя запятая.
"Внутренности" и "лезть" это просторечные слова, нужно перефразировать. Something like "для изоляции деталей реализации от модулей-потребителей"

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +- Также Public API должен защищать интерфейс модуля после рефакторинга - во избежание непредвиденных последствий
Лишнее тире

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +### [`Needs Driven`][refs-needs-driven]
driven

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +Для [проектирования архитектуры][refs-splitting], методология предлагает оперировать [привычными абстракциями][refs-adaptability], но в более консистентном и последовательном порядке.
Первая запятая лишняя

2021-05-13 21:50 UTC, karina-jovian commented on README.md
> +  - **Здесь обсуждаются и разбираются рельные примеры применения, вопросы, проблемы, идеи методологии**
*реальные

2021-05-13 21:50 UTC, karina-jovian commented on docs/concepts/naming-adaptability.md
>  Разрабатывая проект по методологии **feature-sliced** очень важно придерживаться оригинального нейминга, во избежание недопонимания как внутри команды, так и снаружи.
*как среди членов команды, так и за её пределами

2021-05-13 21:50 UTC, karina-jovian commented on docs/concepts/naming-adaptability.md
> +В рамках методологии, каждый из этих терминов имеет [четкое определение](../references/readme.md)
reference нужно поставить в единственное число

2021-05-13 21:50 UTC, karina-jovian commented on README.md
>      > Или если по-вашему этот проект должен развиваться дальше
Лучше бы это вообще убрать

2021-05-13 21:50 UTC, karina-jovian commented on README.md
>    - ⭐ Оцените нас на GitHub, если у вас остались положительные впечатления
Имхо, достаточно оставить только часть до запятой

2021-05-13 21:50 UTC, karina-jovian commented on docs/readme.md
> +- [`Get Started` Знакомство с методологией](get-started)
Форматирование кода ( \`\` ) во всех подобных случаях использовать излишне.

И сразу два языка здесь не вяжутся, нужно выбрать один

2021-05-14 05:05 UTC, martis-git commented on README.md
> -[refs-knowledges]: /docs/references/knowledge-types.md
уже пофикшено

2021-05-14 05:08 UTC, martis-git commented on README.md
> +- Для подключения в другие модули, без нужды лезть во внутренности данного модуля
> Лишняя запятая.

Вот если в остальных местах я убрал личную парцелляцию по твоей просьбе, то тут сорь - иначе теряется акцент на смысле)

2021-05-14 05:09 UTC, martis-git commented on README.md
> +- Также Public API должен защищать интерфейс модуля после рефакторинга - во избежание непредвиденных последствий
Не соглашусь, тут парцелляция разбивает два смысловых блока с акцентами

2021-05-14 05:11 UTC, martis-git commented on README.md
> +### [`Needs Driven`][refs-needs-driven]
- Не оч консистентно выглядит
- Теряется отсылка к `*** Driven Development`
- Выглядит уже не так насыщенно, как с `Need Driven`

![image](https://user-images.githubusercontent.com/42924400/118224450-dc098f80-b48b-11eb-99d3-f812708ec34b.png)

2021-05-14 05:11 UTC, martis-git commented on README.md
> +Для [проектирования архитектуры][refs-splitting], методология предлагает оперировать [привычными абстракциями][refs-adaptability], но в более консистентном и последовательном порядке.
Читать сложно без нее)

2021-05-14 05:11 UTC, martis-git commented on README.md
> +  - **Здесь обсуждаются и разбираются рельные примеры применения, вопросы, проблемы, идеи методологии**
Спс)

2021-05-14 05:13 UTC, martis-git commented on docs/concepts/naming-adaptability.md
> +В рамках методологии, каждый из этих терминов имеет [четкое определение](../references/readme.md)
Я говорил уже - это будет, но под конец недели)
Щас у всех будет уже и так множественное число, поэтому для совместимости пусть останется

2021-05-14 05:17 UTC, martis-git commented on README.md
>      > Или если по-вашему этот проект должен развиваться дальше
Перефразировал, должно быть получше теперь

![image](https://user-images.githubusercontent.com/42924400/118224971-d6607980-b48c-11eb-8783-98c870b11a7c.png)

2021-05-14 05:18 UTC, martis-git commented on README.md
>    - ⭐ Оцените нас на GitHub, если у вас остались положительные впечатления
Имхо, нужно именно тире))

2021-05-14 05:18 UTC, martis-git commented on docs/readme.md
> +- [`Get Started` Знакомство с методологией](get-started)
Оке, ща выясним)

2021-05-14 05:23 UTC, martis-git commented on docs/readme.md
> +- [`Get Started` Знакомство с методологией](get-started)
> Форматирование кода ( `` ) во всех подобных случаях использовать излишне.

Это решил оставить, т.к. путем обычного сравнения - гораздо "консистентнее" выглядит, когда все выражение обернуто в ссылку, а не только текстовая часть

<table>
<td>

![image](https://user-images.githubusercontent.com/42924400/118225294-87ffaa80-b48d-11eb-8e4c-57a2ebdd2ab4.png)

</td>
<td>

![image](https://user-images.githubusercontent.com/42924400/118225298-8930d780-b48d-11eb-87c5-d4dd480981d3.png)

</td>
</table>

2021-05-14 05:26 UTC, martis-git commented on docs/readme.md
> +- [`Get Started` Знакомство с методологией](get-started)
> И сразу два языка здесь не вяжутся, нужно выбрать один

Это:
- Своеобразный "мостик" для привычных аббревиатур в англоязычных доках (человек может "стригерриться" скорее на `Get Started` чем на `Знакомство с методологией`
- Также это связка с имеющимися доками структурно (пока не особо ясно в каком виде будет дока - поэтому немного напоминать лишним не будет)
- Именно в РИДМИ это нужно было чтобы разделить параграфы по смыслу
- И в конце концов - это тупо выглядит лучше, чем обычный текст, имхо (особенно учитывая, что идет ссылка к конкретному разделу)

<table>
<td>

![image](https://user-images.githubusercontent.com/42924400/118225469-e3319d00-b48d-11eb-8f99-0649702f8680.png)
</td>
<td>

![image](https://user-images.githubusercontent.com/42924400/118225472-e593f700-b48d-11eb-864d-bbb0f87ac1f0.png)

</td>
</table>

2021-05-14 05:26 UTC, martis-git commented on docs/readme.md
> +- [`Get Started` Знакомство с методологией](get-started)
Так можно отказаться и от англоязычных хедеров сразу тож))

2021-05-14 05:37 UTC, martis-git commented
@feature-sliced/reviewers можете смотреть)

2021-05-14 08:41 UTC, martis-git commented on docs/readme.md
> +- [`Get Started` Знакомство с методологией](get-started)
Хз крч, варианты распределились)

Имхо, не так критично
![image](https://user-images.githubusercontent.com/42924400/118245229-382edc80-b4a9-11eb-9fff-d2cc4c08b560.png)

2021-05-14 13:52 UTC, ilyaagarkov commented on README.md
> +- Концепция известна также как `Low Coupling & High Cohesion` - для предотвращения неявных связей / сайд-эффектов при разработке и рефакторинге
ощущение что это должно идти уже после описания уровней/слайсов/сегментов
А иначе не понятно о чем вообще речь

2021-05-14 13:55 UTC, ilyaagarkov commented on README.md
> +> **Примечание:** В большинстве случаев рекомендуется располагать `api` и `config` только на shared-слое
что за config вообще не знаю. (да да - у меня label `core team` =) )
но вот по api мы вроде решили что пока вообще никаких ограничений не накдалываем.  То есть я не согласен с `В большинстве случаев рекомендуется`

2021-05-14 14:16 UTC, martis-git commented on README.md
> +> **Примечание:** В большинстве случаев рекомендуется располагать `api` и `config` только на shared-слое
> что за config вообще не знаю

Вот [это](https://t.me/feature_sliced/126))

> но вот по api мы вроде решили что пока вообще никаких ограничений не накдалываем.

Ну да, поэтому и не говорим "запрещаем api располагать вне shared", а [рекоммендуем](https://github.com/feature-sliced/wiki/discussions/66)

*Можно разве что добавить ссылку на дискуссию, как я это [делал](https://github.com/feature-sliced/wiki/blob/3130db24dd5fc690f3c57f9ed96c79c9c0491cc6/docs/guides/migration-from-v1.md#segments) в гайде по миграции*

![image](https://user-images.githubusercontent.com/42924400/118283469-0f720b80-b4d8-11eb-9ea8-7f887f4adafd.png)

2021-05-14 14:21 UTC, martis-git commented on README.md
> +- Концепция известна также как `Low Coupling & High Cohesion` - для предотвращения неявных связей / сайд-эффектов при разработке и рефакторинге
> ощущение что это должно идти уже после описания уровней/слайсов/сегментов

Оке, спасиб - гляну что с этим можно сделать

> К тому же само слово модуль у нас вроде как нигде в самой методологии не используется

Ну хз, имхо - это вродь достаточно распространенный термин)

Почти такой же как "зависимость" / "директория"

![image](https://user-images.githubusercontent.com/42924400/118284197-d5553980-b4d8-11eb-83ef-31a56905e002.png)

2021-05-14 16:01 UTC, sergeysova commented on README.md
> +# feature-sliced
лучше главный заголовок оставлять первым
так гитхабу проще

2021-05-14 16:04 UTC, sergeysova commented on README.md
> +- Концепция известна также как `Low Coupling & High Cohesion` - для предотвращения неявных связей / сайд-эффектов при разработке и рефакторинге
Если юзаем слово "модуль" нужно дать ему определение

2021-05-14 16:06 UTC, sergeysova requested changes

2021-05-14 16:06 UTC, sergeysova commented on README.md
> +- `processes` - бизнес-процессы приложения *(payment, auth, ...)*
```suggestion
- `processes` - бизнес-процессы приложения управляющие страницами *(payment, auth, ...)*
```

2021-05-14 16:06 UTC, sergeysova commented on README.md
> +- *`config` - модуль конфигурации приложения и его окружения*
```suggestion
- `api` - логика взаимодействия с API
- `config` - модуль конфигурации приложения и его окружения
```

2021-05-14 16:44 UTC, martis-git commented on README.md
> +- *`config` - модуль конфигурации приложения и его окружения*
Думаешь, даже визуально не надо выделять api / config?

2021-05-14 16:44 UTC, martis-git commented on README.md
> +- Концепция известна также как `Low Coupling & High Cohesion` - для предотвращения неявных связей / сайд-эффектов при разработке и рефакторинге
> Если юзаем слово "модуль" нужно дать ему определение

Ухх, оке))

Мне казалось это довольно очевидным понятием, даж для методологии

2021-05-14 16:51 UTC, martis-git commented on README.md
> +- Концепция известна также как `Low Coupling & High Cohesion` - для предотвращения неявных связей / сайд-эффектов при разработке и рефакторинге
Добавил его в overview , т.к. оттуда уже начинает использоваться

![image](https://user-images.githubusercontent.com/42924400/118303101-bad98b00-b4ed-11eb-9ffd-dbbf5b90ccca.png)

2021-05-14 16:52 UTC, martis-git commented on README.md
> +- Концепция известна также как `Low Coupling & High Cohesion` - для предотвращения неявных связей / сайд-эффектов при разработке и рефакторинге
*Хотя я бы помянул людей, которые начинают читать методологию, и не знают что такое "модуль"...*

![image](https://user-images.githubusercontent.com/42924400/118303174-cf1d8800-b4ed-11eb-99e9-9f7cf4b3a620.png)

2021-05-14 16:53 UTC, martis-git commented on README.md
> +# feature-sliced
Оке, садимся тогда на еще более кривой стул)

![image](https://user-images.githubusercontent.com/42924400/118303369-08ee8e80-b4ee-11eb-92a7-dccfac778176.png)

2021-05-14 17:07 UTC, AlexandrHoroshih requested changes

2021-05-14 17:07 UTC, AlexandrHoroshih commented on README.md
> +Правила *зависят от конкретного проекта*, и не определяются методологией.
Разжевать бы - например так:
```suggestion
Правила, по которым код разделяется на слайсы, *зависят от конкретного проекта и его бизнес-правил* и не определяются методологией
```

2021-05-15 14:29 UTC, AlexandrHoroshih approved these changes

2021-05-15 15:17 UTC, karina-jovian commented on README.md
> +- Также Public API должен защищать интерфейс модуля после рефакторинга - во избежание непредвиденных последствий
Зачем?

2021-05-15 15:25 UTC, karina-jovian commented on README.md
> +### [`Needs Driven`][refs-needs-driven]
DDD с заглавных букв только потому что это название. Если сделать так в данном заголовке, то он тоже будет выглядеть как название и никак иначе. А ещё возможно тут вообще нужен дефис перед driven вообще.

А при чём тут консистентность, где она нарушается?

2021-05-15 15:31 UTC, martis-git commented on README.md
> +### [`Needs Driven`][refs-needs-driven]
Я уже поправил, как ты просила)

![image](https://user-images.githubusercontent.com/42924400/118369329-c3909680-b5ab-11eb-800b-39d8faa4e1b5.png)

2021-05-15 15:32 UTC, karina-jovian commented on README.md
> +### [`Needs Driven`][refs-needs-driven]
Вообще если посмотреть в каком контексте этот заголовок, то я сомневаюсь что тут это слово подходит, и не уверена что его можно употреблять без существительного ( needs driven [что?] ). Тут бы существительное или пару существительных.

2021-05-15 15:36 UTC, karina-jovian commented on README.md
> +Для [проектирования архитектуры][refs-splitting], методология предлагает оперировать [привычными абстракциями][refs-adaptability], но в более консистентном и последовательном порядке.
@feature-sliced/reviewers нужен ваш фидбэк. Я против запятой, она не обоснована и возможно создаёт лишнюю "запинку" ( паузу ) не только у меня

2021-05-15 15:48 UTC, karina-jovian commented on docs/readme.md
> +- [`Get Started` Знакомство с методологией](get-started)
>человек может "стригерриться" скорее на Get Started чем на Знакомство с методологией

А вот тут сюрприз – именно по этой причине такие слова вообще не переводят и не ставят рядом уточнений

2021-05-15 16:06 UTC, AlexandrHoroshih approved these changes

2021-05-15 16:19 UTC, ilyaagarkov commented on README.md
> +Для [проектирования архитектуры][refs-splitting], методология предлагает оперировать [привычными абстракциями][refs-adaptability], но в более консистентном и последовательном порядке.
Есть четкие правила где запятые нужны, а где нет. Тут нет места  ИМХО
На сколько я знаю, в данном случае не нужны

2021-05-15 20:03 UTC, martis-git commented
Ситуация на 15.05, 23:03

![image](https://user-images.githubusercontent.com/42924400/118376619-c0100600-b5d1-11eb-99c5-b71266e96f67.png)

2021-05-15 20:05 UTC, merged