Docs/concepts/public api
feature-sliced/wiki pull request #76
Opened 2021-03-20 20:36 UTC by AlexandrHoroshih

Changelog:

- Добавил доку о публичном апи модулей приложения

2021-03-20 20:53 UTC, martis-git commented
Заархивировать бы дискуссию основную)

> Как на примере:
![image](https://user-images.githubusercontent.com/42924400/111885216-7c38c000-89d7-11eb-9d4b-94a957333870.png)

2021-03-20 20:56 UTC, AlexandrHoroshih commented
Done

2021-03-20 21:36 UTC, martis-git requested changes
Мне бежать уже пора увы, но вроде как базовое, что в глаза бросалось - отписал

> Старался не придираться особо 😄

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +</details>
```suggestion
</details>

## 📑 См. также
<!-- TODO: Возможно позже надо вынести в md-var -->
- [*Обсуждение* "Public API абстракции"](https://github.com/feature-sliced/wiki/discussions/41)
<!-- TODO: Можно еще повспоминать материалы, где про Public API речь заводилась, мб даже в каком-то из принципов упоминалось -->
```

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +</details>
А, ну думаю можно еще ссыль на проблему файлов-реэкспортов кинуть (т.к. еще still actual)

- https://t.me/iamakulov_channel/558

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +Выполнение этих требований позволяет:
Я бы чуть поменял порядок повествования:

```md
<!-- Основное описание -->

## Цели
... (перечисляем их)

## Требования
... (уже будет понятно, почему такие - т.к. до этого упомянули цели)
```

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +Это выражается в следующих требованиях:
Я бы чутка поменял хедеры в сторону

- `## Цели`
- `## Требования`

> Остальные хедеры (к-рые для каждого конкретного требования), как будто слабо описывают структуру статьи

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +Выполнение этих требований позволяет:
Мб к целям еще что получится добавить, но вродь основное перечислено все

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +- Развязывать руки при переработке внутренней структуры или реализации модуля, т.к. "пользователи" модуля будут затронуты только при ломающих изменениях на уровне публичного интерфейса
Плюс думаю тут и @karina-drummer скажет, но чутка бы поменять формулировку (инфинитив тут мешает скорее)

```suggestion
- Снять ограничения при переработке внутренней структуры или реализации модуля, т.к. "пользователи" модуля будут затронуты только при ломающих изменениях на уровне публичного интерфейса
```

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +Выполнение этих требований позволяет:
И чутка формулировки надо будет наверное подправить, раз это уже "цели", а не "следствия"

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +# Публичное API модуля приложения
Чутка бы снизить долю, если возможно)

![image](https://user-images.githubusercontent.com/42924400/111885811-2d8d2500-89db-11eb-9a93-b99c0fef1ccd.png)

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +# Публичное API модуля приложения
Бросается при прочтении

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +  - удобен для использования остальными частями приложения, в частности, решать проблему коллизии имен
Я бы еще чуть скомпоновал требования, т.к. пока слишком разрозненно выглядит:

> Примерно так это вижу:

```md
## Требования

1. Public API должен осуществлять **контроль доступа для модуля**
   > - Другие части приложения могут использовать **только те сущности модуля, которые представлены в публичном интерфейсе**
   > - Внутренности модуля за пределами публичного интерфейса доступны только самому модулю.

2. Public API должен обладать **анти-хрупкостью**
   > Т.е. сохранять устойчивость модуля к изменениям внутренней реализации

3. Public API должен способствовать **легкой и гибкой интеграции**
    > - Должен предоставлять **публичный интерфейс** для интеграции с остальными частями приложения.
    > - Должен быть удобен для использования остальными частями приложения, в частности, решать проблему коллизии имен
```

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +<details>
Также, не вижу ничего плохого, чтобы спойлеры с кодом и разъяснениями держать ближе к самим требованиям (как и в дискуссии)

![image](https://user-images.githubusercontent.com/42924400/111886011-39c5b200-89dc-11eb-8548-7c10bdb16ef4.png)

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +**Хорошо:** коллизия решена на уровне интерфейса
Я думаю, стоит дополнительно подметить (возможно спрятать под еще один спойлер как в дискуссии), что коллизия должна решаться только на верхнем уровне

Т.к. это не забота "реализации"

![image](https://user-images.githubusercontent.com/42924400/111886063-7a253000-89dc-11eb-9c03-185aabc51d24.png)

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +```
Также бы добавил как "открытый вопрос" проблему реэкспортов, которую не успели обсудить

![image](https://user-images.githubusercontent.com/42924400/111886074-8d380000-89dc-11eb-8b55-3b0d88521c16.png)

Думаю, 
- либо можешь попробовать свое мнение по вопросу изложить, суммируя наше с дискуссии
- либо пометить как "открытый вопрос"
- либо поднять вопрос еще раз, но в чате core-team

2021-03-20 21:36 UTC, martis-git commented on concepts/public-api.md
> +Выполнение этих требований позволяет:
По крайней мере, мне такой порядок кажется более логичным и естественным

2021-03-20 21:37 UTC, martis-git commented on concepts/public-api.md
> +</details>
Почему-то не сохранился коммент - крч я бы добавил раздел "См. также", чтоб человек попавший в статью - видел источник откуда все это началось, да и в целом мог доп. материалы изучить по теме

> Обычно в доках это называется как `See also`, `Further Reading`, `Refs`

2021-03-20 21:37 UTC, martis-git commented on concepts/public-api.md
> +Это выражается в следующих требованиях:
Либо же я не так твой посыл уловил)

2021-03-20 21:38 UTC, martis-git commented on concepts/public-api.md
> +<details>
Тип и проще поддерживать, и при чтении - ты "итеративно" погружаешься к нужному уровню изучения вопроса

2021-03-20 21:43 UTC, martis-git commented
@AlexandrHoroshih плюс. я наверное еще в README указал основном - что такая статья появилось (потом более структурированно будем делать, но пока лучше явно давать знать - что появилась новая дока)

> https://github.com/feature-sliced/wiki/blob/3d8389d3e6491379e6d2cf4983a8ef242653f640/README.md

![image](https://user-images.githubusercontent.com/42924400/111886428-72668b00-89de-11eb-8bed-a2e0f6078037.png)

2021-03-21 18:48 UTC, AlexandrHoroshih commented
@feature-sliced/core

2021-03-22 00:27 UTC, martis-git requested changes
Стало гораздо круче, но спойлеры бы поправить для читаемости (приложил предложения - с ними еще лучше должно стать) 🚀

2021-03-22 00:27 UTC, martis-git commented on concepts/public-api.md
> +</details>
Добавил бы отступы спойлеру, чтобы из флоу дока не выбивался

```suggestion
2. Public API должен быть **анти-хрупким** - устойчивым к изменениям внутри модуля
   - Ломающие изменения поведения модуля отражаются в изменении Public API
   > Например, изменение внутренней структуры не должно приводить к изменению Public API

    <details>

    > **Плохо:** перемещение или переименование этого компонента внутри фичи приведет к необходимости рефакторить импорты во всех местах использования компонента.
    ```diff
    - import { Form } from "features/auth-form/ui/form"
    ```

    > **Хорошо:** интерфейс фичи не отображает её внутреннуюю структуру, внешние "пользователи" фичи не пострадают от перемещения или переименования компонента внутри фичи
    ```diff
    + import { AuthForm } from "features/auth-form"
    ```

    </details>
```

2021-03-22 00:27 UTC, martis-git commented on concepts/public-api.md
> +</details>
- Добавил отступы спойлерам (чтобы из воркфлоу дока не выбивались)
- Вынес спойлеры ближе к самим пунктам (чтобы не было вопросов - к какому из подпунктов каждый спойлер)
- Добавил отдельный пример из дискуссии - для "резолвинг коллизии на уровне Public API"
- Смержил два спойлера (чтобы можно было один раз открыть и увидеть сразу все примеры по пункту - если будут идеи как лучше реализовать/разбить - welcome, но когда на один пункт два разрозненных спойлера - выглядит не оч)

```suggestion
3. Public API должен способствовать **легкой и гибкой интеграции**
   - Должен быть удобен для использования остальными частями приложения, в частности, решать проблему коллизии имен
        <details>

        > **Плохо:** неудобно писать, неудобно читать, "пользователь" фичи страдает
        ```diff
        - import { storeActionUpdateUserDetails } from "features/auth-form"
        - dispatch(storeActionUpdateUserDetails(...))
        ```

        > **Хорошо:** "пользователь" фичи получает доступ к нужным вещам итеративно и гибко
        ```diff
        + import { authFormStore } from "features/auth-form"
        + dispatch(authFormStore.actions.updateUserDetails(...))
        ```

        ---

        > **Плохо:** будет коллизия имен
        ```diff
        - import { Form, store } from "features/auth-form"
        - import { Form, store } from "features/post-form"
        ```

        > **Хорошо:** коллизия решена на уровне интерфейса
        ```diff
        + import { AuthForm, authFormStore } from "features/auth-form"
        + import { AuthForm, postFormStore } from "features/post-form"
        ```

        ```js
        // features/auth-form/index.ts
        export { Form as AuthForm } from "./ui"
        export * as authFormStore from "./model"
        ```

        </details>
   - Коллизия имен должна решаться на уровне публичного интерфейса, а не реализации
        <details>

        > **Плохо:** коллизия не должна резолвиться на уровне реализации
        ```diff
        - export { actions as authFormActions, reducer as authFormReducer } from "./slice"
        -
        - dispatch(authFormActions.foo(...))
        ```

        > **Хорошо:** реализация не думает о коллизиях - это становится заботой только для самой фичи
        ```diff
        + export { actions, reducer } from "./slice"
        + export * as authFormStore  from "./store"   # Feature EntryPoint
        +
        + dispatch(authFormStore.actions.foo(...))
        ```

        </details>
```

2021-03-22 00:27 UTC, martis-git commented on concepts/public-api.md
> +
Добавил пример для требования (немного похож на то что во втором пункте, но тут другой посыл)

```suggestion
1. Public API должен осуществлять **контроль доступа** к содержимому модуля
   - Другие части приложения могут использовать **только те сущности модуля, которые представлены в публичном интерфейсе**
   - Внутренности модуля за пределами публичного интерфейса доступны только самому модулю.

    <details>

    > **Плохо**: Идет обращение напрямую к внутренним частям модуля, минуя публичный интерфейс доступа - опасно, особенно при рефакторинге модуля
    ```diff
    - import { Form } from "features/auth-form/components/view/form"
    - <Form ... />
    ```

    > **Хорошо:** API заранее экспортирует только нужное и разрешенное, разработчику модуля теперь нужно думать только о том, чтобы не ломать Public API при рефакторинге
    ```diff
    + import { AuthForm } from "features/auth-form"
    + <AuthForm ... />
    ```

    </details>

```

2021-03-22 00:28 UTC, martis-git commented on concepts/public-api.md
> +
Вот так это по итогу выглядит

![image](https://user-images.githubusercontent.com/42924400/111926626-a913d280-8abe-11eb-8c6c-4c270e1a44d6.png)

2021-03-22 00:29 UTC, martis-git commented on concepts/public-api.md
> +</details>
Вот так это по итогу выглядит

![image](https://user-images.githubusercontent.com/42924400/111926659-ce084580-8abe-11eb-95ef-079d5b724a58.png)

2021-03-22 00:30 UTC, martis-git commented on concepts/public-api.md
> +</details>
Вот так это выглядит по итогу

![image](https://user-images.githubusercontent.com/42924400/111926691-e710f680-8abe-11eb-84f3-7f3663713f93.png)

2021-03-25 04:08 UTC, martis-git approved these changes
Прям топ вышел, хотя я бы все равно некоторые вещи поправил)

Но если что, потом своим PR позж докину, мб вкусовщина уже

**А так хорошую работу прям проделал, спасибо!**

2021-03-25 04:08 UTC, martis-git commented
@feature-sliced/core заапрувьте еще кто-нить

2021-03-25 10:03 UTC, karina-drummer approved these changes

2021-03-25 10:14 UTC, merged