docs(naming adaptivity): add naming-adaptivity.md
feature-sliced/wiki pull request #77
Opened 2021-03-21 12:02 UTC by ilyaagarkov

2021-03-21 16:02 UTC, martis-git requested changes
Вроде все основное что вспомнил - перенес в ревью)

В целом норм, но есть что улучшить еще 🚀

2021-03-22 08:51 UTC, ilyaagarkov commented
test

2021-03-22 19:59 UTC, ilyaagarkov commented on about/namings-adaptability.md
> +##  Когда следует подменять нейминг?
"Когда следует подумать том, а не поменять ли нейминг?" =)

2021-03-22 20:01 UTC, ilyaagarkov commented on about/namings-adaptability.md
> +<!-- TODO: добавить ссылку на документацию тулинга / пункт адаптация нейминга -->
> Ну го добавим)
имелось ввиду добавить, когда будет тулинг (es-lint плагин, как пример) и документация к нему)

2021-03-23 03:53 UTC, martis-git commented on about/namings-adaptability.md
> +<!-- TODO: добавить ссылку на документацию тулинга / пункт адаптация нейминга -->
Ну я в ЛС ответил)
> `TL;DR:` Лучше чтоб ссыль на доп материалы были, чем нет (особенно на исходные дискуссии-холивары, из которых эта дока и родилась)

2021-03-23 03:57 UTC, martis-git commented on about/namings-adaptability.md
> +##  Когда следует подменять нейминг?
**Я бы старался более короткие имена выбирать)**

Нас итак кириллица подводит из-за anchor ссылок на русском
![image](https://user-images.githubusercontent.com/42924400/112090485-b3a89780-8ba4-11eb-923f-d51261c826ec.png)

Плюс у тебя тут призыв к действию, который мы не обсудили еще)

Можем опять же - в войсе сегодня тему эту поднять 

<details>

То же самое - но с кодировкой (при копировании):

https://github.com/feature-sliced/wiki/blob/c9b8fbd371983e898b7a11cbddb180a4f917c764/about/namings-adaptability.md#%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D0%B5%D1%82-%D0%BF%D0%BE%D0%B4%D0%BC%D0%B5%D0%BD%D1%8F%D1%82%D1%8C-%D0%BD%D0%B5%D0%B9%D0%BC%D0%B8%D0%BD%D0%B3
</details>

> Мб "Когда нейминг может помешать" ?

2021-03-25 04:05 UTC, martis-git commented on about/namings-adaptability.md
> +<!-- TODO: добавить ссылку на документацию тулинга / пункт адаптация нейминга -->
Вот кста пример подходящих доп. материалов

> https://github.com/feature-sliced/wiki/blob/bdb31ab06494932e6c75c24f14881777532d2d5e/concepts/public-api.md#-%D1%81%D0%BC-%D1%82%D0%B0%D0%BA%D0%B6%D0%B5
![image](https://user-images.githubusercontent.com/42924400/112417350-770da500-8d38-11eb-8833-6ac6fe8369ec.png)

2021-03-25 10:30 UTC, ilyaagarkov commented on about/namings-adaptability.md
> +<!-- TODO: добавить ссылку на документацию тулинга / пункт адаптация нейминга -->
Чет я пока не вижу как Public Api / SOLID / GRASP связаны

2021-03-25 11:48 UTC, martis-git commented on about/namings-adaptability.md
> +<!-- TODO: добавить ссылку на документацию тулинга / пункт адаптация нейминга -->
@ilyaagarkov , ну да - это я просто к тому - что в "См. также" можно указывать все, что посчитаешь связанной с темой и что было бы полезно отдельно *поизучать читателю*

2021-03-25 11:59 UTC, martis-git commented on about/namings-adaptability.md
> +В рамках методологии, каждый из этих терминов имеет четкое определение <!-- TODO: добавить ссылку на глоссарий -->
Эх, хз поч тебе этот варик не зашел)

> Сейчас выглядит не оч, но да фиг с ним
![image](https://user-images.githubusercontent.com/42924400/112469591-b65ce580-8d7a-11eb-8faa-0752c5ad738f.png)

2021-03-25 12:28 UTC, martis-git approved these changes

2021-03-25 12:39 UTC, AlexandrHoroshih commented on concepts/naming-adaptability.md
> +
Надо бы явно описать, как справляться с такими ситуациями

2021-03-25 12:42 UTC, AlexandrHoroshih approved these changes

2021-03-25 12:46 UTC, merged