docs(abstractions): add feature description
feature-sliced/wiki pull request #78
Opened 2021-03-21 15:08 UTC by binjospookie

close #71

2021-03-21 16:12 UTC, martis-git commented
@binjospookie пингани (или кинь в чат), как будет готово к ревью

2021-03-21 16:19 UTC, binjospookie commented
@martis-git давай считать за перевью)

у меня есть пара вопросов:
* надо ли раскрыть ещё какие-то аспекты?
* раскрыты ли достаточно описанные аспекты?

2021-03-22 00:33 UTC, martis-git commented
@binjospookie советую ознакомиться с тем, как это ребята делали примерно)

> https://github.com/feature-sliced/wiki/blob/docs/concepts/public-api/concepts/public-api.md
> https://github.com/feature-sliced/wiki/blob/docs/concepts/understanding-needs/concepts/understanding-needs.md

2021-03-22 01:04 UTC, martis-git requested changes
@binjospookie в целом то неплохо, но много что доделать бы еще)

0. **В целом, повторюсь, советую ознакомиться с тем, как это мы с ребятами делали уже (тут прям оч хорошо прослеживаются те правки которые я накидал тебе)**
    - https://github.com/feature-sliced/wiki/blob/docs/concepts/public-api/concepts/public-api.md
    - https://github.com/feature-sliced/wiki/blob/docs/concepts/understanding-needs/concepts/understanding-needs.md

1. Как минимум то что сразу в глаза бросается - **доработать бы в плане структуры и readability для пользователя**
   > Сейчас же хедеров нет и структура не прослеживается
   > А "подробная инфа", к-рая прям всем-всем пользователям не понадобится - не скрывается в спойлерах

2. Вот все 11 правок - это только по форме было)
    **Если же смотреть по тому "чего не хватает содержательно" - то будет еще 20, но для этого как минимум придется еще за тебя работу проделать**

    > Да и ты задолбаешься 30 чужих правок вносить, нежели сам написать сразу полноценно))

    Поэтому прошу еще раз пройтись по [изначальной дискуссии](https://github.com/feature-sliced/wiki/discussions/23) и посмотреть - какие тезисы там выдвигаются

    > Пока же, извини, возникает впечатление, что ты из своих ощущений писал больше
    
    
UPD: Можно пройтись по ~готовой доке, где тоже "бизнес-ценности" и "функциональность" разбираются
> https://github.com/feature-sliced/wiki/blob/docs/concepts/understanding-needs/concepts/understanding-needs.md

<details>

![image](https://user-images.githubusercontent.com/42924400/111929827-87b7e400-8ac8-11eb-93c5-e7011c27eac1.png)

</details>

2021-03-22 01:15 UTC, martis-git commented on about/abstraction/feature.md
> +Feature — изменение в продукте, которое несет ценность пользователю.
Здесь бы еще описания добавить, глянь как у @karina-drummer сделано)

![image](https://user-images.githubusercontent.com/42924400/111928608-2e01ea80-8ac5-11eb-9bb4-3559917d10f9.png)

2021-03-22 09:16 UTC, ilyaagarkov commented on about/abstraction/feature.md
> +
```
├── issues/
│   ├── assignees
│   ├── labels
│   └── milestone
├── actions/
├── marketplace/
```
это же все как раз не фичи, а сущности над которыми и стоятся фичи.

2021-03-22 17:43 UTC, binjospookie commented on about/abstraction/feature.md
> +
Вай нот? Возможность создать issue -- фича. Возможность повесить label на issue -- тоже фича.

2021-03-22 18:31 UTC, ilyaagarkov commented on about/abstraction/feature.md
> +
создать issue это фича, но issue сами по себе это не фича.
Подобные фичи ведут как раз к необходимости импортить фичи из фич.  И как раз эта проблема и привела к появлению такой сущности как entities

2021-03-22 18:36 UTC, binjospookie commented on about/abstraction/feature.md
> +
Готовые issue — результат создания. 

Возможность создания — фича. 
Возможность повесть label — фича. 

Тот же label несёт пользователю ценность, например, можно указать тип issue.

2021-03-22 19:37 UTC, ilyaagarkov commented on about/abstraction/feature.md
> +
Вот именно что не сам label несет ценность, а именно возможность повесть лейбл на что-то несет ценность.
В общем я свое мнение по поводу этого писал тут https://github.com/feature-sliced/wiki/discussions/23#discussioncomment-451017

2021-03-22 21:33 UTC, binjospookie commented on about/abstraction/feature.md
> +
Лейбл в контексте issues. 

Будь ещё какой-то лейбл, то, да, его частя болталась бы в entities.

2021-03-23 03:49 UTC, martis-git commented on about/abstraction/feature.md
> +
Тут больше с @ilyaagarkov соглашусь
> Да и в целом у нас больше людей в core-team, которые считают что фича - конкретная бизнес-ценность и действие ([здесь](https://github.com/feature-sliced/wiki/blob/master/concepts/understanding-needs.md#-tldr) кста тож про это писал)

Я с entities плотно не работал, тож обычно похожим образом на фичи разбивал (labels-list, issue-details и т.д.)

Но похоже на правду - что при разбиении как предлагает @ilyaagarkov и другие ребята (entities + features) - архитектура будет более масштабируемой, читаемой и при этом - сведутся к минимумы необходимости кросс-импортов (а это главный бич сейчас у похожих подходов)

2021-03-23 03:51 UTC, martis-git commented on about/abstraction/feature.md
> +
> Лейбл в контексте issues.
> 
> Будь ещё какой-то лейбл, то, да, его частя болталась бы в entities.

Ну если у тебя лейбл только для ишью (хотя обычно тот же лейбл и на пуллреквесты вешается), то можно его `issue-label` назвать

Чтобы более плоская структура получалась, и не нужно было вкладывать

Хотя с другой стороны, это уже похоже на [проблему `nested-entities`](https://github.com/feature-sliced/wiki/discussions/49)

2021-03-23 03:52 UTC, martis-git commented on about/abstraction/feature.md
> +
@binjospookie @ilyaagarkov можем обсудить попозже в войсе

2021-04-11 17:54 UTC, closed without merging