docs(shared): Add namespace
feature-sliced/wiki pull request #79
Opened 2021-03-21 22:28 UTC by karina-drummer

2021-03-22 00:37 UTC, martis-git commented
Заархивировать бы дискуссию основную)

![image](https://user-images.githubusercontent.com/42924400/111926956-f8a6ce00-8abf-11eb-9f90-9b75737cab6e.png)

2021-03-22 01:09 UTC, martis-git commented
![image](https://user-images.githubusercontent.com/42924400/111928288-34dc2d80-8ac4-11eb-962b-f486b17b779f.png)


Некритично, но я бы старался именовать ветки в соответствие с gitflow (вродь где-то в похожем такое описывалось как раз)

> Глянь как у нас сейчас делают
> ![image](https://user-images.githubusercontent.com/42924400/111928368-6d7c0700-8ac4-11eb-9f0c-1b9bd41f24b9.png)
> https://nvie.com/posts/a-successful-git-branching-model/#feature-branches

2021-03-22 01:28 UTC, martis-git requested changes
Блин, на самом деле, @karina-drummer , я думал от тебя то наоборот **простыня добротного такого текста** получится))

> Я рили стараюсь не придираться особо в PR, но тут... Ну хз, мне кажется как будто ты можешь гораздо мощней написать

## Что не так?
1. Хромает форма документа 
   > Ни структуры, ни форматирования, ни разделения по важности и спойлерам
2. Хромает и содержание
   > Почти ничего из изначальной дискуссии (#14) не увидел здесь
   >
   > Как будто, больше из своих ощущений и представлений писала
   >
   > Плюс есть ощущение, что написание параллельно на англе - будет у тебя только лишние ресурсы занимать - поэтому сама смотри (как минимум тебе сейчас надо вносить правки и в `ru`, и в `en` версию вносить)

<details>

![image](https://user-images.githubusercontent.com/42924400/111929059-65bd6200-8ac6-11eb-8b4b-b62aa7301f1e.png)
</details>

2021-03-22 01:28 UTC, martis-git commented on src/shared/en.md
> +# Namespace: Shared
Ну блен, "just an idea" была же вроде только))

**Мб вынесем в `concepts/abstractions/shared` все же?**
> @binjospookie тоже так сделал

<details>

![image](https://user-images.githubusercontent.com/42924400/111928466-c0ee5500-8ac4-11eb-96e3-4c1bfc106685.png)
</details>

2021-03-22 01:28 UTC, martis-git commented on src/shared/ru.md
> +# Раздел: Shared
Имхо, слово "Раздел" лишнее)

2021-03-22 01:28 UTC, martis-git commented on src/shared/ru.md
> +## Описание
Не, я конечно за readability и "пиши-сокращай" принципы, но не настолько же :DD

![image](https://user-images.githubusercontent.com/42924400/111928631-4540d800-8ac5-11eb-9fc9-143d93ad98b4.png)

2021-03-22 01:28 UTC, martis-git commented on src/shared/ru.md
> +## Описание
1. Где структура?
2. Где форматирование? (все в одну строку на данный момент сейчас читается)
3. Где разделение инфы на важную (то что видно при поверхностном прочтении) и подробную (то что в спойлерах прячем?)
4. Где вообще все то, что в [дискуссии](https://github.com/feature-sliced/wiki/discussions/14) обсуждалось?

2021-03-22 01:28 UTC, martis-git commented on src/shared/en.md
> +# Namespace: Shared
Те модули, где плейсхолдеры заложила - тоже бы адаптировать

> При этом я бы например не клал `api` (и подобные) строго в shared, т.к. это самодостаточная абстракция
>
> И внутри нее уже может дополнительно расписываться смысл если она лежит в shared/feature и т.д.

2021-03-22 01:28 UTC, martis-git commented on src/shared/en.md
> +# Namespace: Shared
Глянь пож, что тут писал

https://github.com/feature-sliced/wiki/discussions/31#discussioncomment-451507

2021-03-22 01:28 UTC, martis-git commented on src/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
Сделал бы отдельно акцент на том, что "shared"-модули оч оторваны от БЛ, и являются более общими, чем те, что выше **(UIKit приложения, основные libs и т.д.)**

> Сейчас же текущаяя формулировка почти подходит и для entities и для features

2021-03-22 01:32 UTC, martis-git commented
Плюс добавил бы в конце все же раздел "См. также"

> [Пример 1](https://github.com/feature-sliced/wiki/blob/docs/concepts/understanding-needs/about/motivation.md)
> [Пример 2](https://github.com/feature-sliced/wiki/blob/docs/concepts/understanding-needs/concepts/understanding-needs.md)

![image](https://user-images.githubusercontent.com/42924400/111929507-93ef7180-8ac7-11eb-8641-20e472cbff6d.png)

2021-03-22 07:16 UTC, karina-drummer commented on src/shared/en.md
> +# Namespace: Shared
> Ну блен, "just an idea" была же вроде только))
> 
> 
> 
> **Мб вынесем в `concepts/abstractions/shared` все же?**
> 
> > @binjospookie тоже так сделал
> 
> 
> 
> <details>
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42924400/111928466-c0ee5500-8ac4-11eb-96e3-4c1bfc106685.png)
> 
> </details>
> 
> 
> 
> 

Я сделала как предложила, остальное up to you. Никакой структуры объявлено не было, а рандомно раскидывать я бы не стала

2021-03-22 07:18 UTC, karina-drummer commented on src/shared/en.md
> +# Namespace: Shared
> Те модули, где плейсхолдеры заложила - тоже бы адаптировать
> 
> 
> 
> > При этом я бы например не клал `api` (и подобные) строго в shared, т.к. это самодостаточная абстракция
> 
> >
> 
> > И внутри нее уже может дополнительно расписываться смысл если она лежит в shared/feature и т.д.

Так мы вроде договорились класть api строго в shared, не?

2021-03-22 07:47 UTC, karina-drummer commented on src/shared/ru.md
> +## Описание
1. Будет шаблон -- будет и структура
2. Переносы строк съелись по какой-то причине, поправлю
3. Жирным шрифтом выделено самое важное, можно даже почти связно это вычитать. Спойлеры -- у нас документация или игра-кликер? Приведи примеры документации где используются спойлеры и дай паттерн по которому их нужно использовать, если это действительно хороший приём, в чём я очень сильно сомневаюсь
4. Распиши что я упустила. Это должен быть готовый вывод, стандарт, а не пересказывание обсуждений, я не права?

2021-03-22 07:56 UTC, karina-drummer commented on src/shared/ru.md
> +# Раздел: Shared
Оторванное от контекста одиного висящее в заголовке слово тоже не вариант. Просто скопировать название каталога недостаточно, Shared что? Нет никаких указаний на то, что документ как-то принадлежит общей структуре.

Вместо "Раздел" возможно есть смысл написать "Домен" и может быть можно опустить двоеточие: "Домен Shared" / "Shared domain"

2021-03-22 07:58 UTC, karina-drummer commented on src/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
Об этом в документе максимально чётко расписано

2021-03-22 08:03 UTC, karina-drummer commented on src/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
"Основные libs" -- ты предлагаешь прямо так и написать? Что такое libs и почему они могут быть основными или неосновными? Это должно быть описано в документе по libs, здесь же только суть самого домена и его содержимое описано в этом контексте

2021-03-22 08:04 UTC, martis-git commented
@karina-drummer пиши выше в комментах пока все что считаешь нужным - чуть позже отвечу обязон

Если же отвечать на твой основной месседж...
<details>

![image](https://user-images.githubusercontent.com/42924400/111956071-63c1c600-8afb-11eb-9464-16fd217b1085.png)
</details>


### `TL;DR:` Дерзай как знаешь и считаешь нужным, но вроде как договаривались всю информативную часть из дискуссии в доки переносить

---
---

> Я несколько раз читала всё что related и по результатам написала строгую техническую выжимку без "может быть" и всяких "А зачем это нужно? Сейчас мы вам ответим, дети", которым место не в доке, а в статьях на medium

1. Да, почти. Вроде как когда мы все обсуждали **задумка была в том, чтобы  "оставить после дискуссии весь информативный сухой остаток"**

2. Никто не просит писать в формате супер приближенных к пользователю статей, но тем не менее, как ты и сама замечаешь - **у людей постоянно возникают повторяющиеся вопросы и им хочется найти от нас или от документации ответы на них**

![image](https://user-images.githubusercontent.com/42924400/111957022-8d2f2180-8afc-11eb-886b-836cc8d4a493.png)

3. Другой аспект еще заключается в том - что *мы закрываем дискуссию, и чаще всего навсегда*, а потому - **хочется собрать выводы на текущем срезе и не возвращаться к этому потом**
    *(Поэтому, как мне кажется - любые проблемные моменты, оставшиеся открытые вопросы - должны быть либо подняты и обсуждены core-team ASAP, либо так чтобы и было указано в доке "Пока это открытый вопрос, мы работаем над этим")*

4. Другой момент - что я в доке вообще не увидел ответов на:
   - "а что выносить в shared? что там должно хоаниться?", 
   - "а могу ли я выносить в shared все что возможно захочу переиспользовать?", 
   - "а что если мы все файлы будем хранить постоянно локально? Что там с DRY"

    И про все это - описано в самой дискуссии, потому даже не знаю что тут сказать (да, там скорее в форме рассуждения, но опять же - можем поднять вопрос в самой core-team)


<details>
<summary>См. что писали по конвертации дискуссии в PR</summary>

![image](https://user-images.githubusercontent.com/42924400/111956741-2dd11180-8afc-11eb-9282-3cce17838b1e.png)
</details>

---

> Да и вообще, какого-то шаблона и конвеншна не было, какое там ещё форматирование нужно я пока слабо представляю, это документация а не конкурс талантов

> Насчёт структуры фс — а есть какой-то способ изобразить её так, чтобы она не ехала и не ломалась? Не стала пока добавлять то, что не имеет надёжных инструментов для отображения. Могу тупо скопипастить, конечно.

Здесь ты тоже права - **закрепленного формата нет, мы его по сути сейчас как раз и формируем**

*Можешь посмотреть на имеющиеся примеры от разных людей наших из core-team:*
- [@AlexandrHoroshih "Public API"](https://github.com/feature-sliced/wiki/blob/docs/concepts/public-api/concepts/public-api.md)
- [@martis-git  "Потребности пользователей"](https://github.com/feature-sliced/wiki/blob/docs/concepts/understanding-needs/concepts/understanding-needs.md)
- [@binjospookie "Что есть feature"](https://github.com/feature-sliced/wiki/pull/78)
- [@ilyaagarkov "Адаптивность нейминга"](https://github.com/feature-sliced/wiki/pull/77)

*У всех в той или иной мере свой стиль, но тем не менее хочется хотя бы увидеть твои собственные идеи касаемо оформления (может мы все тут вообще все неправильно делаем и ты нас щас всех убедишь)*

---

> Так вот, что конкретно я там не увидела? Пока только поняла что стоило "middle-level" вместо "low-level" использовать

Тут не понял, но ладно)

---

> А, сейчас увидела что переносы строк сожрал кто-то, найс

Вот да, потому и полезно проводить `self-review` перед тем как на код ревью кидать - сама бы наверняка тоже увидела

*У нас про self-review и в [contributing-guidelines](https://github.com/feature-sliced/wiki/blob/master/CONTRIBUTING.md#workflow) написано*

2021-03-25 04:17 UTC, martis-git commented on src/shared/en.md
> +# Namespace: Shared
> Я сделала как предложила, остальное up to you. Никакой структуры объявлено не было, а рандомно раскидывать я бы не стала

Я тут скорее к тому - что текст не должен в простыню обычную превращаться, его нужно как-то группировать / разделять по секциям

(как сделаешь окончательный вариант - там посмотрю и по содержанию и по форме - если что сам идеи набросаю)

2021-03-25 04:18 UTC, martis-git commented on src/shared/en.md
> +# Namespace: Shared
> Так мы вроде договорились класть api строго в shared, не?

*Обсудили в войсе*

2021-03-25 04:18 UTC, martis-git commented on src/shared/ru.md
> +# Раздел: Shared
> Оторванное от контекста одиного висящее в заголовке слово тоже не вариант

> Просто скопировать название каталога недостаточно, Shared что? Нет никаких указаний на то, что документ как-то принадлежит общей структуре.

Поч? Не вижу проблем просто оставить `# `shared`

2021-03-25 04:19 UTC, martis-git commented on src/shared/ru.md
> +# Раздел: Shared
> Вместо "Раздел" возможно есть смысл написать "Домен" и может быть можно опустить двоеточие: "Домен Shared" / "Shared domain"

Оверхед как по мне)

Но если второму ревьюверу норм будет - то оке

2021-03-25 04:28 UTC, martis-git commented on src/shared/ru.md
> +## Описание
1. Есть прекрасные слова "инициатива" и "собственное мнение" =)
2. 👌

2021-03-25 04:28 UTC, martis-git commented on src/shared/ru.md
> +## Описание
3.
> @karina-drummer 
> Жирным шрифтом выделено самое важное, можно даже почти связно это вычитать

Сама же ответила на вопрос - "почти связно"))
*У меня лично оч расплывчато удается прочесть такое полотно*

> @karina-drummer 
> Спойлеры -- у нас документация или игра-кликер? Приведи примеры документации где используются спойлеры и дай паттерн по которому их нужно использовать, если это действительно хороший приём, в чём я очень сильно сомневаюсь

**Спойлеры** - это способ отделить основную и важную инфу, от подробностей, до которых не все захотят опускаться

> https://github.com/feature-sliced/wiki/discussions/27#discussioncomment-477546
> ![image](https://user-images.githubusercontent.com/42924400/112418658-fb612780-8d3a-11eb-98af-4548cc2a0015.png)

Да, мб применяется и не во всех документациях (не вспомнишь так сразу), но это **способ разбить огромное полотно текста так, чтобы его мог читать пользователь, и не испугался, когда увидел 100+ размытых строк**

> Думаю тут есть два показательных примера:
> 1. [Как @sergeysova написал о "потребностях пользователей" (в формате оч развернутого комментария)](https://github.com/feature-sliced/wiki/discussions/43)
> 2. [Как о том же самом написал я (тут и `TL;DR`, и разбивка по важности с **заботой о читателе**, и эмоджи, которые как по мне тоже позволяют смягчить масштабность текста и т.д.)](https://github.com/feature-sliced/wiki/blob/master/concepts/understanding-needs.md)

*Само собой, важно не заиграться - и делать спойлеры только там где нужно*
*Но я пока не вижу других путей, чтобы защищать читателей от огромных простыней текста, без разбивки по важности*

2021-03-25 04:31 UTC, martis-git commented on src/shared/ru.md
> +## Описание
4. Лично я вижу это как "текущий срез по дискуссии", даже если там есть неотвеченные вопросы 
> Значит их тем более надо упомянуть в доке, чтобы кто-то задал вопрос в чате или дискуссии и помог его решить до конца

Просто у нас уже порядочно дискуссий накопилось, и потихоньку надо начинать делать из них выжимки
Если же ты во время этого отсечешь слишком много инфы из дискуссии (соглашусь, тут тонкая грань оч), то считай все обсуждение на смарку, т.к
- никто потом не будет за тебя добавлять выводы (да и ты сама вряд ли потом захочешь дополнять и вычитывать все это снова еще раз)
- мало кто потом захочет прочесть еще дискуссию, чтобы понять *"Хм, а не наврал ли мне автор - может там в дискуссии **содержательно** еще что-то есть?"*

2021-03-25 04:32 UTC, martis-git commented on src/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
Оке, просто повторюсь - оч сложно это вычитать

2021-04-04 21:29 UTC, karina-drummer commented on src/shared/ru.md
> +## Описание
>Но я пока не вижу других путей, чтобы защищать читателей от огромных простыней текста, без разбивки по важности

Не нужно никого "защищать", это техническая документация и любой инженер сам должен быть в силах её прочесть, если она будет насколько это возможно написана по стандартам технического языка.

2021-04-04 21:34 UTC, karina-drummer commented on src/shared/ru.md
> +## Описание
<img width="740" alt="image" src="https://user-images.githubusercontent.com/8805308/113522039-42a2b000-95a6-11eb-9fd7-f4664f036d4d.png">

Здесь вообще весь раздел скрыт под спойлер. То есть ты видишь заголовок секции, но чтобы эту секцию прочесть – тебе нужно кликать на спойлер.

2021-04-05 16:51 UTC, martis-git commented on src/shared/ru.md
> +## Описание
> Не нужно никого "защищать", это техническая документация и любой инженер сам должен быть в силах её прочесть, если она будет, насколько это возможно, написана по стандартам технического языка.

> Детали в документации не скрывают – их там расписывают.

Обсудим на созвоне сегодня)

2021-04-05 18:50 UTC, karina-drummer commented
@martis-git я хотела переименовать ветку чтобы привести её к формату, но из-за этого закроется PR. Как поступить?
По самому формату: не уверена что "docs" вообще нужен в названии веток, потому что весь репо про документацию, то есть контекст и так указан

2021-04-05 19:03 UTC, karina-drummer commented
С форматом комментариев к коммитам и заголовков PR: тоже не уверена, что нужно указывать "docs"
Я бы предложила подобный формат:
`basics(philosophy): Fix typo`
`abstractions(domain): Add basic description`
`domains(shared): Add lorem ipsum dolor sit amet`
`domains(shared): Fix description of foobar`

Эти правила как раз можно описать в contribution guide

2021-04-05 21:57 UTC, martis-git commented
> С форматом комментариев к коммитам и заголовков PR: тоже не уверена, что нужно указывать "docs"
Я бы предложила подобный формат:

Упомянул твое мнение в #81 , можем там потом продолжить дискуссию (либо отдельно)

Но как по мне - оверхедно)

Я еще понимаю такое:

- `feat(domains)`
- `fix(concepts)`

Но когда мы и "тип коммита" подстраиваем под методологию... Ну уж извини, мне лично кажется, что это больше про скоуп, а не про тип коммита)

2021-04-05 22:01 UTC, martis-git commented
> @karina-drummer 
> я хотела переименовать ветку чтобы привести её к формату, но из-за этого закроется PR. Как поступить?
По самому формату: не уверена что "docs" вообще нужен в названии веток, потому что весь репо про документацию, то есть контекст и так указан

1. Оставь как есть пока. То что про нейминг веток писал - это "на потом"
2. Касаемо формата - возможно ты и права, но откуда мы можем быть уверены, что потом не появится какая-нибудь кодогенерация и в целом работа с кодом при работе с докой? (что как раз скорее будет соответственно feature/bugfix/refactor)
> Или вот еще задача-баг (#67) - я бы для такой задачи например завел ветку формата `bugfix/**`, поэтому думаю указывать лишний раз `docs` - не особо страшно

2021-04-08 18:43 UTC, karina-drummer commented
@martis-git кстати, about в структуре каталогов ещё более странно смотрится, потому что, опять же, вся документация и есть about

2021-04-08 19:23 UTC, martis-git commented
> @karina-drummer 
> кстати, about в структуре каталогов ещё более странно смотрится, потому что, опять же, вся документация и есть about

Ну никто и не говорил, что это окончательный вариант)

**Если есть предложения - [велком в ишью](https://github.com/feature-sliced/wiki/issues/75)**

> А вообще - хотелось там держать что-то вроде "мета-инфы" о самой методологии (т.е. не ее содержание, а что-то абстрактное, предметное, то что "над методологией" - т.е. как раз ее цели ,видение и т.д.)

![image](https://user-images.githubusercontent.com/42924400/114084637-13978180-98b9-11eb-881e-31c71c73e3c7.png)

2021-04-19 12:28 UTC, karina-drummer commented
Included in #98

2021-04-19 12:28 UTC, closed without merging