docs: add feature description
feature-sliced/wiki pull request #89
Opened 2021-04-11 17:55 UTC by binjospookie

issue #71

2021-04-11 19:38 UTC, martis-git commented
Сегодня мозг гг уже, скорее всего завтра ближе к вечеру только гляну

2021-04-12 07:58 UTC, AlexandrHoroshih requested changes

2021-04-12 07:58 UTC, AlexandrHoroshih commented on concepts/slices/feature.md
> +Изменение в продукте, несущее ценность пользователю.
"Изменение" - я думаю, не самое подходящее слово тут.
Определение из блока в конце (одна фича - одна функциональность), кажется, даже лучше определяет фичу

2021-04-12 08:02 UTC, ilyaagarkov commented on concepts/slices/feature.md
> +Для разработчика: [entity](./entity.md).
почему фильтр по тегам это entity?

Хотя конечно опять же тут лучше обсуждать приложение в целом

2021-04-12 08:03 UTC, binjospookie commented on concepts/slices/feature.md
> +Изменение в продукте, несущее ценность пользователю.
А если что-то меняется в функциональности? 

Пример: чат поддержки. Раньше пользователь вводил свои имя и email, а теперь они подтягиваются из его профиля.

Это ценное для пользователя изменение, хотя сам чат остался чатом.

2021-04-12 08:05 UTC, binjospookie commented on concepts/slices/feature.md
> +Для разработчика: [entity](./entity.md).
Сам по себе фильтр не несёт никакой ценности. Но он может помочь достроить-улучшить фичу, которая имеет в себе какой-то список. 

Емнип, это попадает под определение entity.

2021-04-12 08:27 UTC, ilyaagarkov commented on concepts/slices/feature.md
> +Для разработчика: [entity](./entity.md).
я бы скорее предположил что есть entity tags, а в ней может быть компонент с фильтрами

2021-04-12 08:33 UTC, binjospookie commented on concepts/slices/feature.md
> +Для разработчика: [entity](./entity.md).
Понял тебя. Есть какие-то теги и какой-то список в фиче. Собственно, фича использует теги и на основе данных из них (`selectedTags: string[]`) манипулирует своим списком.

Разумно, да. Раскрою этот момент в примере.

2021-04-12 10:09 UTC, binjospookie commented on concepts/slices/feature.md
> +Для разработчика: [entity](./entity.md).
сделаль

2021-04-12 17:47 UTC, martis-git requested changes
1. А чего предыдущий PR (#78) закрыл?)

Там много правок для лучшения жи, и фундамент для доки заложен

2. Честно скажу - читая вот то что ты написал - у меня не складывается содержательной и единой картины ((

> Мб имеет смысл еще поресерчить что мы в дискуссиях писали? (вродь в ишью кидал ссылки)

2021-04-12 17:51 UTC, binjospookie commented
@martis-git 
1. чтобы не отвлекало, тк формат подачи несколько сменился. Хотя, несколько раз обращался к тому ишью.
Емнип, суть была в том, чтобы не растекаться словами сейчас. 
2. Какую картину ты ожидаешь?

2021-04-14 11:02 UTC, martis-git commented
@binjospookie 

1. Оке, понял)

2. Я хочу получить ответ на вопросы:
- Что такое фича? (т.е. тут и наши холивары как раз - что входит в это понятие)
Как понять, что определенная логика относится к фиче, а не например процессу/странице/entity и т.п.

- Когда у меня логика разделяется на фичи? (т.е. это виджет формы авторизации или же конкретная авторизация, и т.п.)
- Могу ли я группировать фичи? (да, но только папкой, без врапперов-компонентов)
- (Возможно) Почему фичи должны быть изолированными и не зависеть от других? Почему я не могу заимпортить другую? Как быть, если есть общая логика между фичами, и приходится импортить ее как третью фичу?
- (Возможно) Что если моя фича используется для одной страницы? Почему бы мне не хранить ее прям рядом? (one-time-used-features)
- и т.п.

*Как мне кажется* - это базовые вопросы, хотя понятно, что можно еще нагрести при желании

И вот читая доку - я получил ответы на другие вопросы, да, но как уже сказал - цельной картины не вышло((

2021-04-14 14:28 UTC, binjospookie commented
> Что такое фича? (т.е. тут и наши холивары как раз - что входит в это понятие)

В самом начале есть короткое определение.

> Как понять, что определенная логика относится к фиче, а не например процессу/странице/entity и т.п.
> Когда у меня логика разделяется на фичи? (т.е. это виджет формы авторизации или же конкретная авторизация, и т.п.)

Это же один и тот же вопрос заданный по-разному, не?) Тут у меня надежда была на примеры. Надо их дополнить, значит. 


Остальное выкупил.

2021-04-14 15:10 UTC, martis-git commented
> > Что такое фича? (т.е. тут и наши холивары как раз - что входит в это понятие)
> 
> В самом начале есть короткое определение.
> 
> > Как понять, что определенная логика относится к фиче, а не например процессу/странице/entity и т.п.
> > Когда у меня логика разделяется на фичи? (т.е. это виджет формы авторизации или же конкретная авторизация, и т.п.)
> 
> Это же один и тот же вопрос заданный по-разному, не?) Тут у меня надежда была на примеры. Надо их дополнить, значит.
> 
> Остальное выкупил.

Ну я вот перечитал еще раз. Думаю да - немного содержательной части не хватает

Примеры - действительно вроде ок, а вот еще пару-тройку предложений про фичи - я думаю не помешает

2021-04-14 16:28 UTC, binjospookie commented
> Примеры - действительно вроде ок, а вот еще пару-тройку предложений про фичи - я думаю не помешает.

Да, главное не растечься. 

> Почему фичи должны быть изолированными и не зависеть от других? Почему я не могу заимпортить другую? Как быть, если есть общая логика между фичами, и приходится импортить ее как третью фичу?

Звучит как правило.

2021-04-15 00:18 UTC, karina-drummer commented
> > Почему фичи должны быть изолированными и не зависеть от других? Почему я не могу заимпортить другую? Как быть, если есть общая логика между фичами, и приходится импортить ее как третью фичу?
> 
> 
> 
> Звучит как правило. 


> * что-что снова про циклические зависимости *

Но вообще пока что это рекомендация, а не правило. Потому что проблему зависимых фич мы не решили до конца

2021-04-15 05:25 UTC, martis-git commented
> Потому что проблему зависимых фич мы не решили до конца

Ну кста да. Т.е. как минимум стоит написать что - "нужно юзать entitites" и разбивать логику там

Либо сегодня на созвоне обсудить этот кейс уже наконец

2021-04-15 08:36 UTC, binjospookie commented
> Но вообще пока что это настоятельная рекомендация, а не правило.

Соглы

>  Т.е. как минимум стоит написать что - "нужно юзать entitites" и разбивать логику там

Ещё можно внизу оставить ссылку на `entity`. Что-то типа "смотри так же". Наверное, у любой страницы доки должно быть такое, чтобы как раз "провести за ручку"

2021-04-22 03:36 UTC, karina-drummer commented on concepts/slices/feature.md
> +Изменение в продукте, несущее ценность пользователю.
Может, здесь вообще использовать что-то вроде "единица функциональности"?

2021-05-10 13:33 UTC, binjospookie commented
> Ещё можно внизу оставить ссылку на entity. Что-то типа "смотри так же". Наверное, у любой страницы доки должно быть такое, чтобы как раз "провести за ручку"

или эе это должно быть частью сайта с докой

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/8722478/117667345-7a0c0a00-b1ad-11eb-9cdc-5c6829a2145c.png">

2021-05-10 14:00 UTC, martis-git commented on concepts/slices/feature.md
> +
Предлагаю еще добавить, что фичи могут группироваться **по папкам**)

> Но не с доп. логикой - иначе у нас возникают nested-features
>
> Группировка нужна только для того чтобы структурно все похожие фичи лежали в одном месте
>
> По-моему на публичном созвоне обсуждали как раз

```sh
- features/order   # Группа фич
   - add-to-cart    # Полноценная фича
         - ui/
         - model/
         - index.ts
   - total-info       # Полноценная фича
         - ui/
         - model/
         - index.ts
   -  index.tx  # Публичный API с реэкспортом фич
```

> Как раз недавний пример с пет-проекта

2021-05-10 14:03 UTC, martis-git commented on concepts/slices/feature.md
> +3) как данные представлены для пользователя
Оч некритично

```suggestion
1) Какие данные нужны для её работы
2) По каким правилами происходят изменения данных
3) Какие [entities](./entity.md) нужны для полного построения фичи
4) Как данные представлены для пользователя
```

2021-05-10 14:09 UTC, martis-git commented on concepts/slices/feature.md
> +С точки зрения кода: не все изменения для пользователя — `features`, но все `features` — изменения для пользователя.
Ну вот для MVP, может и пойдет

Но я бы еще подумал (особенно учитывая комментарии @AlexandrHoroshih  и @karina-jovian ) как можно улучшить определение)

Возможно что-то вроде `Часть функциональности, несущая бизнес-ценность пользователю`

2021-05-10 17:01 UTC, binjospookie commented on concepts/slices/feature.md
> +С точки зрения кода: не все изменения для пользователя — `features`, но все `features` — изменения для пользователя.
> несущая бизнес-ценность пользователю

фичи (как и продукты) делаются для пользователей. сама по себе "бизнес-ценность" ценности не несёт. бизнес исходит из проблем/болей пользователей.

очень важно понимать, что во главе всей этой истории именно пользователь

2021-05-10 18:00 UTC, martis-git commented on concepts/slices/feature.md
> +С точки зрения кода: не все изменения для пользователя — `features`, но все `features` — изменения для пользователя.
Ну тогда что-то вроде `Часть бизнес-функциональности, несущая ценность/пользу пользователю`

Или как Саша ниже предложил

2021-05-10 18:39 UTC, binjospookie commented on concepts/slices/feature.md
> +Изменение в продукте, несущее ценность пользователю.
Так изменение не функциональности, а изменение в продукте. 

Раньше в саппорт писать можно было только по почте, а теперь через чат. 

Подтягивание email автокомплитом в чате — улучшение, которое позволяет пользователю сосредоточиться на чтении и написании. Более того, отсутствие автокомплита можно расценивать как баг, а его появление как фикс.

2021-05-10 18:48 UTC, binjospookie commented on concepts/slices/feature.md
> +Изменение в продукте, несущее ценность пользователю.
Возможно, добавляя словосочетание "в рамках методологи", всё встаёт на свои места.

2021-05-10 18:58 UTC, binjospookie commented on concepts/slices/feature.md
> +Изменение в продукте, несущее ценность пользователю.
С другой стороны, замена "изменение" на "функциональность" может уменьшить количество вопросов а-ля: "я перекрасил кнопку, это ли не фича?"

2021-05-10 18:59 UTC, karina-jovian approved these changes

2021-05-10 19:07 UTC, binjospookie commented on references/layers/feature.md
> +
> А разрешены ли вложенные фичи?

одна фича - одна функциональность => нет

2021-05-10 19:11 UTC, binjospookie commented
@AlexandrHoroshih u won!

2021-05-10 19:20 UTC, martis-git commented on concepts/slices/feature.md
> +Изменение в продукте, несущее ценность пользователю.
> Появление функциональности в продукте — его изменение?

Ну просто имхо, тут ты рассматриваешь понятие фича только в рамках добавления новой функциональности)

А еще ведь можно модифицировать одну, вторую - удалить, а третью вообще смерджить с другой

Поэтому "изменение в продукте" - ну немного диссонанс вызывает при прочтении, хз))

2021-05-10 19:29 UTC, martis-git commented on references/layers/feature.md
> +
> одна фича - одна функциональность => нет

Ну типа да - я так и ответил)

Но надо развернуть , как их группировать потом

2021-05-10 19:30 UTC, martis-git commented on references/layers/feature.md
> +
> потому что инсталлится конкретный пакет, а не пакет фичей жеж
соответственно, и index какой-то не нужен

Ну потому что скорее всего каждый пакет у вас более самодостаточен и не так нуждается в пласте многих фичей, как огроменные проекты, имхо)

2021-05-10 19:40 UTC, AlexandrHoroshih approved these changes

2021-05-11 04:02 UTC, martis-git approved these changes
Если не лень - то можешь глянуть оставшиеся правки

А так все ок)

2021-05-11 04:02 UTC, martis-git commented on references/layers/feature.md
> +
Я бы всеж присмотрелся к этому))

> Если нет - значит сам потом буду пушить эту идею ахах

```suggestion

### Группировка фич

Часто возникает необходимость как-то собрать вместе ряд несколько связанных по смыслу фич *(при этом они могут не импортировать друг друга напрямую)*

Методология рекоммендует избегать **вложенных фич**, т.е. фич - которые сильно связаны под общей оберткой с доп. логикой

Вместое этого - методология предлагает при необходимости - **группировать по папкам** необходимые фичи *(при этом нельзя эти фичи связывать напрямую, папки нужны только для структурной группировки по смыслу)*

```sh
features/order             # Группа фич
    ├── add-to-cart/       # Полноценная фича
    ├── total-info/        # Полноценная фича
    └── index.ts/          # Файл с реэкспортом (при необходимости)
```

2021-05-11 08:44 UTC, ilyaagarkov commented on references/layers/feature.md
> +
какое то очень странно определени.
Почему что-то для пользователя это фича, а для разработчка нет?

Разве суть методологии не том чтобы соединить эти два мира? Чтобы фича бала фичей для всех

2021-05-11 08:51 UTC, ilyaagarkov commented on references/layers/feature.md
> +Одним из инструментов для её решения является [entity](./entity.md).
Не очень понятно, почему entity это средство решения этой проблемы?
Ну если конечно ты не знаком с историей методологии. 
Но даже тут, entities это не средство решение этой проблемы, а результат переосмысления всего подхода.

2021-05-11 09:10 UTC, martis-git commented on references/layers/feature.md
> +Одним из инструментов для её решения является [entity](./entity.md).
Ну то что ты связность разбиваешь по двум слоям

Тут явно про это не напишешь, но этому и хочется завести `guides/low-coupling.md` где про это все будет написано

2021-05-11 09:10 UTC, martis-git commented on references/layers/feature.md
> +Одним из инструментов для её решения является [entity](./entity.md).
Можно было бы и тут расписать - но тогда уже под конец @binjospookie затюкаем)

2021-05-11 09:12 UTC, binjospookie commented on references/layers/feature.md
> +
А если продуктовнер считает фичей наличие подсказки под полем, то это тоже надо в фичу класть?

2021-05-11 10:47 UTC, binjospookie commented on references/layers/feature.md
> +
![image](https://user-images.githubusercontent.com/8722478/117803498-60c39600-b25f-11eb-9f6a-54063d6bccbe.jpeg)

Не пишем

2021-05-11 17:06 UTC, martis-git commented on references/layers/feature.md
> +
@ilyaagarkov @binjospookie Предлагаю подумать до завтра

Если не подберем лучше - то заливаем как есть

Все равно до конца недели еще будет возможность внести свои правки

(плюсаните если вам ок)

2021-05-12 08:29 UTC, merged