chore(templates): add pull-request-template
feature-sliced/wiki pull request #90
Opened 2021-04-12 16:54 UTC by martis-git

## Чеклист

- [ ] `docs` Использован материал с дискуссий

- [ ] `by-issue` - Проведена проверка по требованиям задачи

- [x] Проведено self-review изменений

## CHANGELOG

- Решил добавить темплейт для PR, для доп. соблюдения качества в пулл-реквестах

2021-04-12 17:00 UTC, binjospookie submitted a review, later dismissed

2021-04-12 21:29 UTC, karina-drummer requested changes

2021-04-12 21:29 UTC, karina-drummer commented on .github/pull_request_template.md
> +2. Сверьтесь с чеклистом самоконтроля и отметьте нужные пункты по завершению
"чеклист самоконтроля" хорошо бы заменить на "чеклист", потому что он и так подразумевает самоконтроль

2021-04-12 21:29 UTC, karina-drummer commented on .github/pull_request_template.md
> +- [ ] `docs` Использован материал с дискуссий
"Материал с дискуссий" звучит косноязычно, предлагаю что-то типа "Использованы выводы из дискуссий" ( ну или хотя бы прямо так )

2021-04-12 21:38 UTC, martis-git commented on .github/pull_request_template.md
> +2. Сверьтесь с чеклистом самоконтроля и отметьте нужные пункты по завершению
Доеб засчитан)

2021-04-12 21:39 UTC, martis-git commented on .github/pull_request_template.md
> +- [ ] `docs` Использован материал с дискуссий
А вот в том и проблема - что выводов чаще всего в дискуссиях нет)

Я тож так хотел написать

> "Использованы дискуссии" - на этом остановлюсь наверн

2021-04-12 21:52 UTC, karina-drummer commented on .github/pull_request_template.md
> +- [ ] `docs` Использован материал с дискуссий
Или "Учтены дискуссии" 🤔

2021-04-14 06:37 UTC, martis-git commented
@binjospookie @karina-drummer Внес правки - аппрувните пож, если все ок

2021-04-14 08:12 UTC, binjospookie approved these changes

2021-04-14 09:28 UTC, martis-git commented
@binjospookie  спасибо!

@karina-drummer ОКни пож тоже

2021-04-14 17:36 UTC, ilyaagarkov approved these changes

2021-04-15 00:07 UTC, karina-drummer approved these changes

2021-04-15 00:08 UTC, merged